const nbData = {
    new: {
        women: [
            {
                idx: 1,
                name: "와이드 라운드 버클 단화 2.0 HPWWVD217M",
                img: "item_1",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {
                idx: 2,
                name: "바게트 숄더백 HPABGD202M",
                img: "item_2",
                oprice:"",
                dprice: "39900",
                sale:"",
            },
            {   idx:3,
                name: "네프사 캔디컬러 미들 삭스 HPAO5DA18Q",
                img: "item_3",
                oprice:"",
                dprice: "5900",
                sale:"",
            },
            {
                idx:4,
                name: "[경량EVA] 더블 스트랩 리커버리 슬리퍼 HPCV4D244M",
                img: "item_4",
                oprice:"25900",
                dprice: "24900",
                sale:"",
            },
            {   idx:5,
                name: "[경량EVA] 아웃도어 투 벨크로 샌들 HPCV4D242M",
                img: "item_5",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:6,
                name: "[도영도영이 PICK] 캔버스 쇼퍼백 HPABGD225M",
                img: "item_6",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:7,
                name: "캔버스 핸드폰백 HPABGD226M",
                img: "item_7",
                oprice:"25900",
                dprice: "24900",
                sale:"",
            },
            {   idx:8,
                name: "캔버스 버킷백 HPABGD224M",
                img: "item_8",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:9,
                name: "[경량EVA] 논슬립 베이직 리커버리 쪼리 HPCV5D251M",
                img: "item_9",
                oprice:"19900",
                dprice: "18900",
                sale:"",
            },
            {   idx:10,
                name: "링클 버킷햇 HPACSD304M",
                img: "item_10",
                oprice:"29900",
                dprice: "27900",
                sale:"",
            },
            {   idx:11,
                name: "[도영도영이 PICK] 코튼 블렌드 케이블 버킷햇 HPACSD301M",
                img: "item_11",
                oprice:"29900",
                dprice: "27900",
                sale:"",
            },
            {   idx:12,
                name: "라운드 투스트랩 밴딩 슬라이드 1.0 HPWWID231D",
                img: "item_12",
                oprice:"19900",
                dprice: "18900",
                sale:"",
            },
            {   idx:13,
                name: "[경량EVA] 논슬립 페인팅 리커버리 쪼리 HPCV5D382M",
                img: "item_13",
                oprice:"29900",
                dprice: "27900",
                sale:"",
            },
            {   idx:14,
                name: "[경량EVA] 컬러풀 리커버리 클로그 HPCV4D386M",
                img: "item_14",
                oprice:"35900",
                dprice: "33900",
                sale:"",
            },
            {   idx:15,
                name: "[테니스클럽] 그래픽 골지 미들 삭스 HPAO5DA17Q",
                img: "item_15",
                oprice:"",
                dprice: "5900",
                sale:"",
            },
            {   idx:16,
                name: "에스파듀 패턴 샌들 2.0 HPWWND321Q",
                img: "item_16",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:17,
                name: "에스파듀 패턴 슬라이드 2.0 HPWWID321Q",
                img: "item_17",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:18,
                name: "네이비 3M 스트링 백팩 HPADZC401N",
                img: "item_18",
                oprice:"59900",
                dprice: "53900",
                sale:"",
            },
            {   idx:19,
                name: "밴딩 첼시 레인부츠 HPCV7D383W",
                img: "item_19",
                oprice:"35900",
                dprice: "33900",
                sale:"",
            },
            {   idx:20,
                name: "캐스퍼 미니 토트백 TPBT79W32",
                img: "item_20",
                oprice:"25900",
                dprice: "19900",
                sale:"",
            },
        ],
        men: [
            {   idx:1,
                name: "아이스락 하이퍼그립 첼시부츠 (HPMV9C404M RE) HPMV9DA04M",
                img: "item_1",
                oprice:"",
                dprice: "159000",
                sale:"",
            },
            {   idx:2,
                name: "[슈탠다드] 남성 컬러 골지크루 삭스 HPAO5DA19M",
                img: "item_2",
                oprice:"",
                dprice: "3900",
                sale:"",
            },
            {   idx:3,
                name: "마하그리드 스트링 백팩 HPADZDA05M",
                img: "item_3",
                oprice:"59900",
                dprice: "56900",
                sale:"",
            },
            {   idx:4,
                name: "[드로우핏 X 슈펜] 베이직 레더 더비 HPMR7CA51M",
                img: "item_4",
                oprice:"",
                dprice: "129000",
                sale:"",
            },
            {   idx:5,
                name: "🌟TOP 5 [오솔라이트] 유니 레더 독일군 HPMR6DA03M",
                img: "item_5",
                oprice:"",
                dprice: "59900",
                sale:"",
            },
            {   idx:6,
                name: "이지라이트 컴포트 어텁 레이스 펀칭더비 BYSL79A12",
                img: "item_6",
                oprice:"39900",
                dprice: "23630",
                sale:"",
            },
            {   idx:7,
                name: "네이비 3M 스트링 백팩 HPADZC401N",
                img: "item_7",
                oprice:"59900",
                dprice: "53900",
                sale:"",
            },
            {   idx:8, 
                name: "[핏더사이즈X슈펜] Seku-shi(세쿠시) 첼시 부읏츠 (다크 브라운 / 아이보리)",
                img: "item_8",
                oprice:"",
                dprice: "159000",
                sale:"",
            },
            {   idx:9,
                name: "22 베이직 키높이 스니커즈_HPMR6CA04M",
                img: "item_9",
                oprice:"59900",
                dprice: "53900",
                sale:"",
            },
            {   idx:10,
                name: "남성 레더 드라이빙로퍼_스웨이드 페니(HPMR9C471M RE) HPMR9DA11M",
                img: "item_10",
                oprice:"79900",
                dprice: "75900",
                sale:"",
            },
            {   idx:11,
                name: "드로우핏 X 슈펜 로퍼 HPMR7DA56M",
                img: "item_11",
                oprice:"79900",
                dprice: "75900",
                sale:"",
            },
            {   idx:12,
                name: "드로우핏 X 슈펜 더비 HPMR7DA55M",
                img: "item_12",
                oprice:"79900",
                dprice: "75900",
                sale:"",
            },
            {   idx:13,
                name: "[초경량] 논슬립 슬림 슈레이스 워킹화 HPCR5DA23M",
                img: "item_13",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:14,
                name: "[초경량] 논슬립 베이직 슬립온 워킹화 HPCR5DA31Q",
                img: "item_14",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:15,
                name: "유니 모던 캐주얼 키높이 더비 HPMR7DA02M",
                img: "item_15",
                oprice:"59900",
                dprice: "56900",
                sale:"",
            },
            {   idx:16,
                name: "유니 모던 캐주얼 로퍼 HPMR7DA04Q",
                img: "item_16",
                oprice:"59900",
                dprice: "56900",
                sale:"",
            },
            {   idx:17,
                name: "유니모던 캐주얼 더비 HPMR7DA01Q",
                img: "item_17",
                oprice:"59900",
                dprice: "56900",
                sale:"",
            },
            {   idx:18,
                name: "[NAVY] 2포켓 빅 반달 메신저백 HPABCD206M",
                img: "item_18",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:19,
                name: "[NAVY] 가벼운 반달포켓 크로스백 HPABCD207M",
                img: "item_19",
                oprice:"29900",
                dprice: "27900",
                sale:"",
            },
            {   idx:20,
                name: "남성 베이직 쿠션 샌들 HPMV4D210M",
                img: "item_20",
                oprice:"59900",
                dprice: "56900",
                sale:"",
            },
        ],
        kids: [
            {   idx:1,
                name: "[디즈니] 앨리스 라이팅 샌들 HPKWND21DG",
                img: "item_1",
                oprice:"39900",
                dprice: "35900",
                sale:"",
            },
            {   idx:2,
                name: "키즈 샤이닝 레인부츠 HPKV6DA01Q",
                img: "item_2",
                oprice:"29900",
                dprice: "26910",
                sale:"",
            },
            {   idx:3,
                name: "키즈 크레용 버클 쿠션 샌들 HPKWND212G",
                img: "item_3",
                oprice:"29900",
                dprice: "26910",
                sale:"",
            },
            {   idx:4,
                name: "[디즈니] 앨리스 하트 크로스백 HPKBXDA1DG",
                img: "item_4",
                oprice:"35900",
                dprice: "32310",
                sale:"",
            },
            {   idx:5,
                name: "키즈 플랫폼 베이직 샌들 HPKWND211G",
                img: "item_5",
                oprice:"29900",
                dprice: "26910",
                sale:"",
            },
            {   idx:6,
                name: "키즈 썸머 스트랩 쿠션 샌들 HPKV4D202U",
                img: "item_6",
                oprice:"29900",
                dprice: "26910",
                sale:"",
            },
            {   idx:7,
                name: "[디즈니] 앨리스 헤어핀 세트 HPKZZDA1DG",
                img: "item_7",
                oprice:"19900",
                dprice: "17910",
                sale:"",
            },
            {   idx:8, 
                name: "[레인보우] 리본 탈부착 글리터 플랫 HPKWVD224G",
                img: "item_8",
                oprice:"29900",
                dprice: "24220",
                sale:"",
            },
            {   idx:9,
                name: "키즈 경량 리커버리 샌들 HPKV0D202U",
                img: "item_9",
                oprice:"29900",
                dprice: "25900",
                sale:"",
            },
            {   idx:10,
                name: "키즈 버클 EVA 샌들 HPKV4D201U",
                img: "item_10",
                oprice:"29900",
                dprice: "25900",
                sale:"",
            },
            {   idx:11,
                name: "키즈 스마일 스니커즈 4족 세트 HPKL4DA07U",
                img: "item_11",
                oprice:"9900",
                dprice: "9400",
                sale:"",
            },
            {   idx:12,
                name: "키즈 치즈 스니커즈 4족 세트 HPKL4DA08U",
                img: "item_12",
                oprice:"9900",
                dprice: "9400",
                sale:"",
            },
            {   idx:13,
                name: "여아 유니콘 스니커즈 4족 세트 HPKL4DA09G",
                img: "item_13",
                oprice:"9900",
                dprice: "9400",
                sale:"",
            },
            {   idx:14,
                name: "키즈 스트라이프 덧신 5족 세트 HPKL4DA06U",
                img: "item_14",
                oprice:"9900",
                dprice: "9400",
                sale:"",
            },
            {   idx:15,
                name: "키즈 스트라이프 스니커즈 5족 세트 HPKL4DA05U",
                img: "item_15",
                oprice:"9900",
                dprice: "9400",
                sale:"",
            },
            {   idx:16,
                name: "키즈 컬러블록 스니커즈 4족 세트 HPKL4DA04U",
                img: "item_16",
                oprice:"9900",
                dprice: "9400",
                sale:"",
            },
            {   idx:17,
                name: "[레인보우] 레이스 토오픈 라이팅 구두 HPKWVD225G",
                img: "item_17",
                oprice:"39900",
                dprice: "35910",
                sale:"",
            },
            {   idx:18,
                name: "키즈 메리제인 쿠션플랫 HPKWFD205G",
                img: "item_18",
                oprice:"29900",
                dprice: "26910",
                sale:"",
            },
            {   idx:19,
                name: "키즈 메쉬 버킷햇 HPKACD201U",
                img: "item_19",
                oprice:"29900",
                dprice: "26910",
                sale:"",
            },
            {   idx:20,
                name: "키즈 경량 EVA 샌들 HPKV0D204U",
                img: "item_20",
                oprice:"25900",
                dprice: "23310",
                sale:"",
            },
        ],
    },
    best: {
        women: [
            {   idx:1,
                name: "바게트 숄더백 HPABGD202M",
                img: "item_2",
                oprice:"",
                dprice: "39900",
                sale:"",
            },
            {   idx:2,
                name: "와이드 라운드 버클 단화 2.0 HPWWVD217M",
                img: "item_1",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:3,
                name: "네프사 캔디컬러 미들 삭스 HPAO5DA18Q",
                img: "item_3",
                oprice:"",
                dprice: "5900",
                sale:"",
            },
            {   idx:4,
                name: "[경량EVA] 더블 스트랩 리커버리 슬리퍼 HPCV4D244M",
                img: "item_4",
                oprice:"25900",
                dprice: "24900",
                sale:"",
            },
            {   idx:5,
                name: "[경량EVA] 아웃도어 투 벨크로 샌들 HPCV4D242M",
                img: "item_5",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:6,
                name: "[도영도영이 PICK] 캔버스 쇼퍼백 HPABGD225M",
                img: "item_6",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:7,
                name: "캔버스 핸드폰백 HPABGD226M",
                img: "item_7",
                oprice:"25900",
                dprice: "24900",
                sale:"",
            },
            {   idx:8,
                name: "캔버스 버킷백 HPABGD224M",
                img: "item_8",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:9,
                name: "[경량EVA] 논슬립 베이직 리커버리 쪼리 HPCV5D251M",
                img: "item_9",
                oprice:"19900",
                dprice: "18900",
                sale:"",
            },
            {   idx:10,
                name: "링클 버킷햇 HPACSD304M",
                img: "item_10",
                oprice:"29900",
                dprice: "27900",
                sale:"",
            },
            {   idx:11,
                name: "[도영도영이 PICK] 코튼 블렌드 케이블 버킷햇 HPACSD301M",
                img: "item_11",
                oprice:"29900",
                dprice: "27900",
                sale:"",
            },
            {   idx:12,
                name: "라운드 투스트랩 밴딩 슬라이드 1.0 HPWWID231D",
                img: "item_12",
                oprice:"19900",
                dprice: "18900",
                sale:"",
            },
            {   idx:13,
                name: "[경량EVA] 논슬립 페인팅 리커버리 쪼리 HPCV5D382M",
                img: "item_13",
                oprice:"29900",
                dprice: "27900",
                sale:"",
            },
            {   idx:14,
                name: "[경량EVA] 컬러풀 리커버리 클로그 HPCV4D386M",
                img: "item_14",
                oprice:"35900",
                dprice: "33900",
                sale:"",
            },
            {   idx:15,
                name: "[테니스클럽] 그래픽 골지 미들 삭스 HPAO5DA17Q",
                img: "item_15",
                oprice:"",
                dprice: "5900",
                sale:"",
            },
            {   idx:16,
                name: "에스파듀 패턴 샌들 2.0 HPWWND321Q",
                img: "item_16",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:17,
                name: "에스파듀 패턴 슬라이드 2.0 HPWWID321Q",
                img: "item_17",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:18,
                name: "네이비 3M 스트링 백팩 HPADZC401N",
                img: "item_18",
                oprice:"59900",
                dprice: "53900",
                sale:"",
            },
            {   idx:19,
                name: "밴딩 첼시 레인부츠 HPCV7D383W",
                img: "item_19",
                oprice:"35900",
                dprice: "33900",
                sale:"",
            },
            {   idx:20,
                name: "캐스퍼 미니 토트백 TPBT79W32",
                img: "item_20",
                oprice:"25900",
                dprice: "19900",
                sale:"",
            },
        ],
        men: [
            {   idx:1,
                name: "뉴덮개 슬리퍼 AFDB20S26",
                img: "item_1",
                oprice:"15900",
                dprice: "13900",
                sale:"",
            },
            {   idx:2,
                name: "🌟TOP 5 [오솔라이트] 유니 레더 독일군 HPMR6DA03M",
                img: "item_2",
                oprice:"59900",
                dprice: "56900",
                sale:"",
            },
        ],
        kids: [
            {   idx:1,
                name: "키즈 피셔맨 말랑 젤리샌들 HPKV1D204U",
                img: "item_1",
                oprice:"17910",
                dprice: "16120",
                sale:"",
            },
            {   idx:2,
                name: "피셔맨 말랑젤리 샌들 VKDJ78S04",
                img: "item_2",
                oprice:"19900",
                dprice: "11900",
                sale:"",
            },
        ],
    },
}

const tgData = {
    women: {
        shoes: {
            flat: [
                {
                    idx: 1,
                    gender: "ALL",
                    name:"🌟TOP 5 [가드너] 스윗버튼 메리제인 플랫 1.0 HPWWFD202S",
                    img: "item_1",
                    oprice: "29900",
                    dprice: "28900",
                    sale: "3",
                    review: "170"
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name:"V컷 스퀘어 쿠션 플랫 1.0 HPWWFC401S",
                    img: "item_2",
                    oprice: "19900",
                    dprice: "14880",
                    sale: "25",
                    review: "63"
                },
            ],
            sandal: [
                {
                    idx: 1,
                    gender: "ALL",
                    name: "패턴 커버 플랫 샌들 1.5 MIDW78S14",
                    img: "item_1",
                    oprice:"19900",
                    dprice: "16900",
                    sale:"",
                    review: "83",
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name:"플랫폼 피셔맨 샌들 3.5 HPWWND204M",
                    img:"item_2",
                    oprice:"39900",
                    dprice:"35910",
                    sale:"",
                    review:"33",
                },
            ],
        },
        bags: {
            backpack: [
                {
                    idx: 1,
                    gender: "ALL",
                    name: "푸우 레이 백팩 TPBK79S52",
                    img: "item_1",
                    oprice: "20930",
                    dprice: "18840",
                    sale:"",
                    review: "23",
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name: "[테디아일랜드] 베이직 백팩 HPADZDA01C",
                    img: "item_2",
                    oprice: "23920",
                    dprice: "21530",
                    sale:"",
                    review: "1",
                },
                {
                    idx: 3,
                    gender: "ALL",
                    name: "전황일콜라보 매쉬백팩 TPBK79W72",
                    img: "item_3",
                    oprice: "48930",
                    dprice: "44040",
                    sale:"",
                    review: "10",
                },
            ]     ,
            minibag: [
                {
                    idx: 1,
                    gender: "ALL",
                    name: "크로셰 핸드폰 백 BLBK78S11",
                    img: "item_1",
                    oprice: "11130",
                    dprice: "10020",
                    sale:"",
                    review: "4",
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name: "나일론 셔링 미니백 HPABGD221M",
                    img: "item_2",
                    oprice: "20720",
                    dprice: "18650",
                    sale:"",
                    review: "1",
                },
                {
                    idx: 3,
                    gender: "ALL",
                    name: "데일리 나일론 미니 숄더백 HPABGC407M",
                    img: "item_3",
                    oprice: "20930",
                    dprice: "18840",
                    sale:"",
                    review: "2",
                },
            ]       

        },
        ac: {
            socks: [
                {
                    idx: 1,
                    gender: "ALL",
                    name: "슈탠다드 남녀 데일리 페이크 삭스 10팩 LGKA79A01",
                    img: "item_1",
                    oprice: "12530",
                    dprice: "11280",
                    sale:"",
                    review: "65",
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name: "슈탠다드 양말_남녀 쇼트 10팩 LGKA79A21",
                    img: "item_2",
                    oprice: "12530",
                    dprice: "11280",
                    sale:"",
                    review: "5",
                },
                {
                    idx: 3,
                    gender: "ALL",
                    name: "슈탠다드 양말_남녀 클래식 골지 7팩 LGKA20A07",
                    img: "item_3",
                    oprice: "9030",
                    dprice: "8130",
                    sale:"",
                    review: "46",
                },
            ],
            hat: [
                {
                    idx: 1,
                    gender: "ALL",
                    name: "[도영도영이 PICK] 코튼 블렌드 케이블 버킷햇 HPACSD301M",
                    img: "item_1",
                    oprice: "23920",
                    dprice: "21530",
                    sale:"",
                    review: "4",
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name: "아일렛 베이직 버킷햇 TPCH79W02",
                    img: "item_2",
                    oprice: "13930",
                    dprice: "12540",
                    sale:"",
                    review: "11",
                },
                {
                    idx: 3,
                    gender: "ALL",
                    name: "화섬 소프트 베이직 볼캡 TPCC79W02",
                    img: "item_3",
                    oprice: "7000",
                    dprice: "6300",
                    sale:"",
                    review: "25",
                },
            ]
        }
    },
    men: {
        shoes: {
            sneakers: [
                {
                    idx: 1,
                    gender: "ALL",
                    name:"[슈탠다드] 와이드핏 캔버스 스니커즈 HPCR3DA03M",
                    img:"item_1",
                    oprice:"29900",
                    dprice:"27900",
                    sale:"",
                    review:"126",
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name:"[슈탠다드] 베이직 캔버스 스니커즈 HPCR3DA01M",
                    img:"item_2",
                    oprice:"29900",
                    dprice:"27900",
                    sale:"",
                    review:"98",
                },
                {   
                    idx:3,
                    gender: "ALL",
                    name:"[NAVY] 베이직 캔버스 덱 슈즈 HPCR3CA03S",
                    img:"item_3",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"9",
                },
                {   
                    idx:4,
                    gender: "ALL",
                    name:"메쉬 스포츠 스트랩 캐주얼 AFDM78S65",
                    img:"item_4",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"6",
                },
                {   
                    idx:5,
                    gender: "ALL",
                    name:"슬립온 니트 워킹화 AFHJ79S01",
                    img:"item_5",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"37",
                },
            ],

            slippers: [
                {   
                    idx: 1,
                    gender: "ALL",
                    name: "남성 피셔맨 오픈 슬라이드 HPMV4D207M",
                    img: "item_1",
                    oprice:"49900",
                    dprice: "46900",
                    sale:"",
                    review:"5",
                },
                {   
                    idx: 2,
                    gender: "ALL",
                    name: "[핏더사이즈] 남성 리커버리 슬라이드 HPMV4DA11M",
                    img: "item_2",
                    oprice:"39900",
                    dprice: "35900",
                    sale:"",
                    review:"12",
                },
            ]
        },
        bags: {
            crossbag: [
                {
                    idx: 1,
                    gender: "ALL",
                    name: "마하 그리드 유틸리티 에코백 TPBT78S76",
                    img: "item_1",
                    oprice: "20,930",
                    dprice: "18,840",
                    sale: "",
                    review: "19",
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name: "[드로우핏 X 슈펜] 투포켓 크로스백 HPABFC404D",
                    img: "item_2",
                    oprice: "39920",
                    dprice: "35930",
                    sale: "",
                    review: "11",
                },
                {
                    idx: 3,
                    gender: "ALL",
                    name: "전황일 패딩 버킷백 TPBT79W15",
                    img: "item_3",
                    oprice: "18130",
                    dprice: "16320",
                    sale: "",
                    review: "16",
                },
            ],
            mensbag: [
                {
                    idx: 1,
                    gender: "ALL",
                    name: "비슬로우 BESLOWⅩSHOOPEN 메신저백 TPBF79S09",
                    img: "item_1",
                    oprice: "34930",
                    dprice: "31440",
                    sale: "",
                    review: "17", 
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name: "비슬로우 BESLOW Ⅹ SHOOPEN 포켓 토트백 TPBF79S07",
                    img: "item_2",
                    oprice: "41930",
                    dprice: "37740",
                    sale: "",
                    review: "6", 
                },
                {
                    idx: 3,
                    gender: "ALL",
                    name: "SHOO NOTEBOOK BAG TPBF79S04",
                    img: "item_3",
                    oprice: "34930",
                    dprice: "31440",
                    sale: "",
                    review: "24", 
                },
            ]
        },
        ac: {
            belt: [
                {
                    idx: 1,
                    gender: "ALL",
                    name: "빈티지 버클 레더벨트 3.0 TPFL78A02",
                    img: "item_1",
                    oprice: "20930",
                    dprice: "18840",
                    sale: "",
                    review: "1", 
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name: "FG 무봉제_벨트 TPFL79A05",
                    img: "item_2",
                    oprice: "20930",
                    dprice: "18840",
                    sale: "",
                    review: "8", 
                },
                {
                    idx: 3,
                    gender: "ALL",
                    name: "컬러패턴 S 마스크 목걸이 BLAZ79A03",
                    img: "item_3",
                    oprice: "1330",
                    dprice: "1200",
                    sale: "",
                    review: "19", 
                },
            ],
            hat: [
                {
                    idx: 1,
                    gender: "ALL",
                    name: "아일렛 베이직 버킷햇 TPCH79W02",
                    img: "item_1",
                    oprice: "13930",
                    dprice: "12540",
                    sale: "",
                    review: "11",
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name: "네이비 볼록자수 볼캡 HPACCCA51M",
                    img: "item_2",
                    oprice: "13930",
                    dprice: "12540",
                    sale: "",
                    review: "4",
                },
                {
                    idx: 3,
                    gender: "ALL",
                    name: "뽀글이 군밤모자 HPAHOD109M",
                    img: "item_3",
                    oprice: "23920",
                    dprice: "21530",
                    sale: "",
                    review: "7",
                },
            ]

        },
    },
    kids: {
        shoes: {
            shoe: [
                {
                    idx: 1,
                    gender: "ALL",
                    name: "키즈 플라워 매쉬 쿠션플랫 VKST78S5M",
                    img: "item_1",
                    oprice: "9900",
                    dprice: "8910",
                    sale: "",
                    review: "3",
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name: "키즈 니트 말랑쿠션 플랫 VKST78S01",
                    img: "item_2",
                    oprice: "9900",
                    dprice: "8910",
                    sale: "",
                    review: "6",
                },
                {
                    idx: 3,
                    gender: "ALL",
                    name: "[레인보우] 리본 탈부착 글리터 플랫 HPKWVD224G",
                    img: "item_3",
                    oprice: "12900",
                    dprice: "11610",
                    sale: "",
                    review: "1",
                },
            ],
            sandal: [
                {
                    idx: 1,
                    gender: "ALL",
                    name: "키즈 플라워 매쉬 쿠션플랫 VKST78S5M",
                    img: "item_1",
                    oprice: "9900",
                    dprice: "8910",
                    sale: "",
                    review: "3",
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name: "키즈 니트 말랑쿠션 플랫 VKST78S01",
                    img: "item_2",
                    oprice: "9900",
                    dprice: "8910",
                    sale: "",
                    review: "6",
                },
                {
                    idx: 3,
                    gender: "ALL",
                    name: "[레인보우] 리본 탈부착 글리터 플랫 HPKWVD224G",
                    img: "item_3",
                    oprice: "12900",
                    dprice: "11610",
                    sale: "",
                    review: "1",
                },
            ]
        },
        bags: {
            slipperbag: [
                {
                    idx: 1,
                    gender: "ALL",
                    name: "[뉴스쿨] 키즈 크로스 신발주머니 HPKBMDA02U",
                    img: "item_1",
                    oprice: "15900",
                    dprice: "14310",
                    sale: "",
                    review: "2",
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name: "레디셋고 신발주머니 VKBT78S02",
                    img: "item_2",
                    oprice: "8900",
                    dprice: "8010",
                    sale: "",
                    review: "7",
                },
                {
                    idx: 3,
                    gender: "ALL",
                    name: "[뉴스쿨] 키즈 베이직 신발주머니 HPKBMDA01U",
                    img: "item_3",
                    oprice: "8900",
                    dprice: "8010",
                    sale: "",
                    review: "4",
                },
                {
                    idx: 4,
                    gender: "ALL",
                    name: "베이직 신발 주머니 VKBT79S01",
                    img: "item_4",
                    oprice: "12900",
                    dprice: "11610",
                    sale: "",
                    review: "26",
                },
            ],
            stylebag: [
                {
                    idx: 1,
                    gender: "ALL",
                    name: "[뉴스쿨] 키즈 슬링백 HPKBXDA01U",
                    img: "item_1",
                    oprice: "20900",
                    dprice: "18810",
                    sale: "",
                    review: "",
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name: "키즈 목걸이 지갑 HPKBXDA03U",
                    img: "item_2",
                    oprice: "12900",
                    dprice: "11610",
                    sale: "",
                    review: "2",
                },
                {
                    idx: 3,
                    gender: "ALL",
                    name: "키즈 화섬 미니 크로스백 HPKBXDA02U",
                    img: "item_3",
                    oprice: "20900",
                    dprice: "18810",
                    sale: "",
                    review: "",
                },
                {
                    idx: 4,
                    gender: "ALL",
                    name: "겨울왕국 뽀글이 크로스백 VKBX79W1D",
                    img: "item_4",
                    oprice: "14900",
                    dprice: "13410",
                    sale: "",
                    review: "",
                },
            ]

        },
        ac: {
            socks: [
                {
                    idx: 1,
                    gender: "ALL",
                    name: "키즈 체크 스포츠 양말 4족세트 HPKL8DA01U",
                    img: "item_1",
                    oprice: "10900",
                    dprice: "9810",
                    sale: "",
                    review: "14",
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name: "키즈 스마일 스포츠 양말 4족 세트 HPKL8DA03U",
                    img: "item_2",
                    oprice: "10900",
                    dprice: "9810",
                    sale: "",
                    review: "12",
                },
                {
                    idx: 3,
                    gender: "ALL",
                    name: "키즈 치즈 스니커즈 4족 세트 HPKL4DA08U",
                    img: "item_3",
                    oprice: "8900",
                    dprice: "8010",
                    sale: "",
                    review: "",
                },
                {
                    idx: 4,
                    gender: "ALL",
                    name: "키즈 펄 레이스 양말 3족 세트 HPKL6DA03G",
                    img: "item_4",
                    oprice: "8900",
                    dprice: "8010",
                    sale: "",
                    review: "",
                },
            ],
            hat: [
                {
                    idx: 1,
                    gender: "ALL",
                    name: "키즈 메쉬 버킷햇 HPKACD201U",
                    img: "item_1",
                    oprice: "23900",
                    dprice: "21510",
                    sale: "",
                    review: "",
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name: "키즈 썬캡 HPKACD203U",
                    img: "item_2",
                    oprice: "20900",
                    dprice: "18810",
                    sale: "",
                    review: "22",
                },
                {
                    idx: 3,
                    gender: "ALL",
                    name: "[테니스클럽] 키즈 배색 볼캡 HPKACDA03U",
                    img: "item_3",
                    oprice: "15900",
                    dprice: "14310",
                    sale: "",
                    review: "1",
                },
                {
                    idx: 4,
                    gender: "ALL",
                    name: "키즈 메쉬 플랩캡 HPKACD202U",
                    img: "item_4",
                    oprice: "23900",
                    dprice: "21510",
                    sale: "",
                    review: "11",
                },
            ]
        }
    }
}

export { nbData, tgData };