const nbData = {
    new: {
        women: [
            {
                idx: 1,
                name: "와이드 라운드 버클 단화 2.0 HPWWVD217M",
                img: "item_1",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {
                idx: 2,
                name: "바게트 숄더백 HPABGD202M",
                img: "item_2",
                oprice:"",
                dprice: "39900",
                sale:"",
            },
            {   idx:3,
                name: "네프사 캔디컬러 미들 삭스 HPAO5DA18Q",
                img: "item_3",
                oprice:"",
                dprice: "5900",
                sale:"",
            },
            {
                idx:4,
                name: "[경량EVA] 더블 스트랩 리커버리 슬리퍼 HPCV4D244M",
                img: "item_4",
                oprice:"25900",
                dprice: "24900",
                sale:"",
            },
            {   idx:5,
                name: "[경량EVA] 아웃도어 투 벨크로 샌들 HPCV4D242M",
                img: "item_5",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:6,
                name: "[도영도영이 PICK] 캔버스 쇼퍼백 HPABGD225M",
                img: "item_6",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:7,
                name: "캔버스 핸드폰백 HPABGD226M",
                img: "item_7",
                oprice:"25900",
                dprice: "24900",
                sale:"",
            },
            {   idx:8,
                name: "캔버스 버킷백 HPABGD224M",
                img: "item_8",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:9,
                name: "[경량EVA] 논슬립 베이직 리커버리 쪼리 HPCV5D251M",
                img: "item_9",
                oprice:"19900",
                dprice: "18900",
                sale:"",
            },
            {   idx:10,
                name: "링클 버킷햇 HPACSD304M",
                img: "item_10",
                oprice:"29900",
                dprice: "27900",
                sale:"",
            },
            {   idx:11,
                name: "[도영도영이 PICK] 코튼 블렌드 케이블 버킷햇 HPACSD301M",
                img: "item_11",
                oprice:"29900",
                dprice: "27900",
                sale:"",
            },
            {   idx:12,
                name: "라운드 투스트랩 밴딩 슬라이드 1.0 HPWWID231D",
                img: "item_12",
                oprice:"19900",
                dprice: "18900",
                sale:"",
            },
            {   idx:13,
                name: "[경량EVA] 논슬립 페인팅 리커버리 쪼리 HPCV5D382M",
                img: "item_13",
                oprice:"29900",
                dprice: "27900",
                sale:"",
            },
            {   idx:14,
                name: "[경량EVA] 컬러풀 리커버리 클로그 HPCV4D386M",
                img: "item_14",
                oprice:"35900",
                dprice: "33900",
                sale:"",
            },
            {   idx:15,
                name: "[테니스클럽] 그래픽 골지 미들 삭스 HPAO5DA17Q",
                img: "item_15",
                oprice:"",
                dprice: "5900",
                sale:"",
            },
            {   idx:16,
                name: "에스파듀 패턴 샌들 2.0 HPWWND321Q",
                img: "item_16",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:17,
                name: "에스파듀 패턴 슬라이드 2.0 HPWWID321Q",
                img: "item_17",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:18,
                name: "네이비 3M 스트링 백팩 HPADZC401N",
                img: "item_18",
                oprice:"59900",
                dprice: "53900",
                sale:"",
            },
            {   idx:19,
                name: "밴딩 첼시 레인부츠 HPCV7D383W",
                img: "item_19",
                oprice:"35900",
                dprice: "33900",
                sale:"",
            },
            {   idx:20,
                name: "캐스퍼 미니 토트백 TPBT79W32",
                img: "item_20",
                oprice:"25900",
                dprice: "19900",
                sale:"",
            },
        ],
        men: [
            {   idx:1,
                name: "아이스락 하이퍼그립 첼시부츠 (HPMV9C404M RE) HPMV9DA04M",
                img: "item_1",
                oprice:"",
                dprice: "159000",
                sale:"",
            },
            {   idx:2,
                name: "[슈탠다드] 남성 컬러 골지크루 삭스 HPAO5DA19M",
                img: "item_2",
                oprice:"",
                dprice: "3900",
                sale:"",
            },
            {   idx:3,
                name: "마하그리드 스트링 백팩 HPADZDA05M",
                img: "item_3",
                oprice:"59900",
                dprice: "56900",
                sale:"",
            },
            {   idx:4,
                name: "[드로우핏 X 슈펜] 베이직 레더 더비 HPMR7CA51M",
                img: "item_4",
                oprice:"",
                dprice: "129000",
                sale:"",
            },
            {   idx:5,
                name: "🌟TOP 5 [오솔라이트] 유니 레더 독일군 HPMR6DA03M",
                img: "item_5",
                oprice:"",
                dprice: "59900",
                sale:"",
            },
            {   idx:6,
                name: "이지라이트 컴포트 어텁 레이스 펀칭더비 BYSL79A12",
                img: "item_6",
                oprice:"39900",
                dprice: "23630",
                sale:"",
            },
            {   idx:7,
                name: "네이비 3M 스트링 백팩 HPADZC401N",
                img: "item_7",
                oprice:"59900",
                dprice: "53900",
                sale:"",
            },
            {   idx:8, 
                name: "[핏더사이즈X슈펜] Seku-shi(세쿠시) 첼시 부읏츠 (다크 브라운 / 아이보리)",
                img: "item_8",
                oprice:"",
                dprice: "159000",
                sale:"",
            },
            {   idx:9,
                name: "22 베이직 키높이 스니커즈_HPMR6CA04M",
                img: "item_9",
                oprice:"59900",
                dprice: "53900",
                sale:"",
            },
            {   idx:10,
                name: "남성 레더 드라이빙로퍼_스웨이드 페니(HPMR9C471M RE) HPMR9DA11M",
                img: "item_10",
                oprice:"79900",
                dprice: "75900",
                sale:"",
            },
            {   idx:11,
                name: "드로우핏 X 슈펜 로퍼 HPMR7DA56M",
                img: "item_11",
                oprice:"79900",
                dprice: "75900",
                sale:"",
            },
            {   idx:12,
                name: "드로우핏 X 슈펜 더비 HPMR7DA55M",
                img: "item_12",
                oprice:"79900",
                dprice: "75900",
                sale:"",
            },
            {   idx:13,
                name: "[초경량] 논슬립 슬림 슈레이스 워킹화 HPCR5DA23M",
                img: "item_13",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:14,
                name: "[초경량] 논슬립 베이직 슬립온 워킹화 HPCR5DA31Q",
                img: "item_14",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:15,
                name: "유니 모던 캐주얼 키높이 더비 HPMR7DA02M",
                img: "item_15",
                oprice:"59900",
                dprice: "56900",
                sale:"",
            },
            {   idx:16,
                name: "유니 모던 캐주얼 로퍼 HPMR7DA04Q",
                img: "item_16",
                oprice:"59900",
                dprice: "56900",
                sale:"",
            },
            {   idx:17,
                name: "유니모던 캐주얼 더비 HPMR7DA01Q",
                img: "item_17",
                oprice:"59900",
                dprice: "56900",
                sale:"",
            },
            {   idx:18,
                name: "[NAVY] 2포켓 빅 반달 메신저백 HPABCD206M",
                img: "item_18",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:19,
                name: "[NAVY] 가벼운 반달포켓 크로스백 HPABCD207M",
                img: "item_19",
                oprice:"29900",
                dprice: "27900",
                sale:"",
            },
            {   idx:20,
                name: "남성 베이직 쿠션 샌들 HPMV4D210M",
                img: "item_20",
                oprice:"59900",
                dprice: "56900",
                sale:"",
            },
        ],
        kids: [
            {   idx:1,
                name: "[디즈니] 앨리스 라이팅 샌들 HPKWND21DG",
                img: "item_1",
                oprice:"39900",
                dprice: "35900",
                sale:"",
            },
            {   idx:2,
                name: "키즈 샤이닝 레인부츠 HPKV6DA01Q",
                img: "item_2",
                oprice:"29900",
                dprice: "26910",
                sale:"",
            },
            {   idx:3,
                name: "키즈 크레용 버클 쿠션 샌들 HPKWND212G",
                img: "item_3",
                oprice:"29900",
                dprice: "26910",
                sale:"",
            },
            {   idx:4,
                name: "[디즈니] 앨리스 하트 크로스백 HPKBXDA1DG",
                img: "item_4",
                oprice:"35900",
                dprice: "32310",
                sale:"",
            },
            {   idx:5,
                name: "키즈 플랫폼 베이직 샌들 HPKWND211G",
                img: "item_5",
                oprice:"29900",
                dprice: "26910",
                sale:"",
            },
            {   idx:6,
                name: "키즈 썸머 스트랩 쿠션 샌들 HPKV4D202U",
                img: "item_6",
                oprice:"29900",
                dprice: "26910",
                sale:"",
            },
            {   idx:7,
                name: "[디즈니] 앨리스 헤어핀 세트 HPKZZDA1DG",
                img: "item_7",
                oprice:"19900",
                dprice: "17910",
                sale:"",
            },
            {   idx:8, 
                name: "[레인보우] 리본 탈부착 글리터 플랫 HPKWVD224G",
                img: "item_8",
                oprice:"29900",
                dprice: "24220",
                sale:"",
            },
            {   idx:9,
                name: "키즈 경량 리커버리 샌들 HPKV0D202U",
                img: "item_9",
                oprice:"29900",
                dprice: "25900",
                sale:"",
            },
            {   idx:10,
                name: "키즈 버클 EVA 샌들 HPKV4D201U",
                img: "item_10",
                oprice:"29900",
                dprice: "25900",
                sale:"",
            },
            {   idx:11,
                name: "키즈 스마일 스니커즈 4족 세트 HPKL4DA07U",
                img: "item_11",
                oprice:"9900",
                dprice: "9400",
                sale:"",
            },
            {   idx:12,
                name: "키즈 치즈 스니커즈 4족 세트 HPKL4DA08U",
                img: "item_12",
                oprice:"9900",
                dprice: "9400",
                sale:"",
            },
            {   idx:13,
                name: "여아 유니콘 스니커즈 4족 세트 HPKL4DA09G",
                img: "item_13",
                oprice:"9900",
                dprice: "9400",
                sale:"",
            },
            {   idx:14,
                name: "키즈 스트라이프 덧신 5족 세트 HPKL4DA06U",
                img: "item_14",
                oprice:"9900",
                dprice: "9400",
                sale:"",
            },
            {   idx:15,
                name: "키즈 스트라이프 스니커즈 5족 세트 HPKL4DA05U",
                img: "item_15",
                oprice:"9900",
                dprice: "9400",
                sale:"",
            },
            {   idx:16,
                name: "키즈 컬러블록 스니커즈 4족 세트 HPKL4DA04U",
                img: "item_16",
                oprice:"9900",
                dprice: "9400",
                sale:"",
            },
            {   idx:17,
                name: "[레인보우] 레이스 토오픈 라이팅 구두 HPKWVD225G",
                img: "item_17",
                oprice:"39900",
                dprice: "35910",
                sale:"",
            },
            {   idx:18,
                name: "키즈 메리제인 쿠션플랫 HPKWFD205G",
                img: "item_18",
                oprice:"29900",
                dprice: "26910",
                sale:"",
            },
            {   idx:19,
                name: "키즈 메쉬 버킷햇 HPKACD201U",
                img: "item_19",
                oprice:"29900",
                dprice: "26910",
                sale:"",
            },
            {   idx:20,
                name: "키즈 경량 EVA 샌들 HPKV0D204U",
                img: "item_20",
                oprice:"25900",
                dprice: "23310",
                sale:"",
            },
        ],
    },
    best: {
        women: [
            {   idx:1,
                name: "바게트 숄더백 HPABGD202M",
                img: "item_2",
                oprice:"",
                dprice: "39900",
                sale:"",
            },
            {   idx:2,
                name: "와이드 라운드 버클 단화 2.0 HPWWVD217M",
                img: "item_1",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:3,
                name: "네프사 캔디컬러 미들 삭스 HPAO5DA18Q",
                img: "item_3",
                oprice:"",
                dprice: "5900",
                sale:"",
            },
            {   idx:4,
                name: "[경량EVA] 더블 스트랩 리커버리 슬리퍼 HPCV4D244M",
                img: "item_4",
                oprice:"25900",
                dprice: "24900",
                sale:"",
            },
            {   idx:5,
                name: "[경량EVA] 아웃도어 투 벨크로 샌들 HPCV4D242M",
                img: "item_5",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:6,
                name: "[도영도영이 PICK] 캔버스 쇼퍼백 HPABGD225M",
                img: "item_6",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:7,
                name: "캔버스 핸드폰백 HPABGD226M",
                img: "item_7",
                oprice:"25900",
                dprice: "24900",
                sale:"",
            },
            {   idx:8,
                name: "캔버스 버킷백 HPABGD224M",
                img: "item_8",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:9,
                name: "[경량EVA] 논슬립 베이직 리커버리 쪼리 HPCV5D251M",
                img: "item_9",
                oprice:"19900",
                dprice: "18900",
                sale:"",
            },
            {   idx:10,
                name: "링클 버킷햇 HPACSD304M",
                img: "item_10",
                oprice:"29900",
                dprice: "27900",
                sale:"",
            },
            {   idx:11,
                name: "[도영도영이 PICK] 코튼 블렌드 케이블 버킷햇 HPACSD301M",
                img: "item_11",
                oprice:"29900",
                dprice: "27900",
                sale:"",
            },
            {   idx:12,
                name: "라운드 투스트랩 밴딩 슬라이드 1.0 HPWWID231D",
                img: "item_12",
                oprice:"19900",
                dprice: "18900",
                sale:"",
            },
            {   idx:13,
                name: "[경량EVA] 논슬립 페인팅 리커버리 쪼리 HPCV5D382M",
                img: "item_13",
                oprice:"29900",
                dprice: "27900",
                sale:"",
            },
            {   idx:14,
                name: "[경량EVA] 컬러풀 리커버리 클로그 HPCV4D386M",
                img: "item_14",
                oprice:"35900",
                dprice: "33900",
                sale:"",
            },
            {   idx:15,
                name: "[테니스클럽] 그래픽 골지 미들 삭스 HPAO5DA17Q",
                img: "item_15",
                oprice:"",
                dprice: "5900",
                sale:"",
            },
            {   idx:16,
                name: "에스파듀 패턴 샌들 2.0 HPWWND321Q",
                img: "item_16",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:17,
                name: "에스파듀 패턴 슬라이드 2.0 HPWWID321Q",
                img: "item_17",
                oprice:"39900",
                dprice: "37900",
                sale:"",
            },
            {   idx:18,
                name: "네이비 3M 스트링 백팩 HPADZC401N",
                img: "item_18",
                oprice:"59900",
                dprice: "53900",
                sale:"",
            },
            {   idx:19,
                name: "밴딩 첼시 레인부츠 HPCV7D383W",
                img: "item_19",
                oprice:"35900",
                dprice: "33900",
                sale:"",
            },
            {   idx:20,
                name: "캐스퍼 미니 토트백 TPBT79W32",
                img: "item_20",
                oprice:"25900",
                dprice: "19900",
                sale:"",
            },
        ],
        men: [
            {   idx:1,
                name: "뉴덮개 슬리퍼 AFDB20S26",
                img: "item_1",
                oprice:"15900",
                dprice: "13900",
                sale:"",
            },
            {   idx:2,
                name: "🌟TOP 5 [오솔라이트] 유니 레더 독일군 HPMR6DA03M",
                img: "item_2",
                oprice:"59900",
                dprice: "56900",
                sale:"",
            },
        ],
        kids: [
            {   idx:1,
                name: "키즈 피셔맨 말랑 젤리샌들 HPKV1D204U",
                img: "item_1",
                oprice:"17910",
                dprice: "16120",
                sale:"",
            },
            {   idx:2,
                name: "피셔맨 말랑젤리 샌들 VKDJ78S04",
                img: "item_2",
                oprice:"19900",
                dprice: "11900",
                sale:"",
            },
        ],
    },
}

const tgData = {
    women: {
        shoes: {
            flat: [
                {
                    idx: 1,
                    gender: "ALL",
                    name:"🌟TOP 5 [가드너] 스윗버튼 메리제인 플랫 1.0 HPWWFD202S",
                    img: "item_1",
                    oprice: "29900",
                    dprice: "28900",
                    sale: "3",
                    review: "170"
                },
                {
                    idx: 2,
                    gender: "ALL",
                    name:"V컷 스퀘어 쿠션 플랫 1.0 HPWWFC401S",
                    img: "item_2",
                    oprice: "19900",
                    dprice: "14880",
                    sale: "25",
                    review: "63"
                },
                // 여기부터
                {   
                    name:"쿠션 플랫 1.0 HPWWFCA01S",
                    img: "item_3",
                    oprice: "19900",
                    dprice: "14880",
                    sale: "25",
                    review: "127"
                },
                {   
                    name:"[가드너] 스퀘어 리본 플랫슈즈 HPWWFDA01S",
                    img: "item_4",
                    oprice: "25900",
                    dprice: "24900",
                    sale: "73",
                    review: "3"
                },
                {   
                    name:"와이드 라운드 버클 단화 2.0 HPWWVD217M",
                    img: "item_5",
                    oprice: "39900",
                    dprice: "37900",
                    sale: "45",
                    review: "29"
                },
                {   
                    name:"베이직 메리제인 플랫 1.0 HPWWFC402S",
                    img: "item_6",
                    oprice: "19900",
                    dprice: "14880",
                    sale: "25",
                    review: "129"
                },
                {   
                    name:"스퀘어 힐밴딩 플랫 1.0 MIST78S02",
                    img: "item_7",
                    oprice: "19900",
                    dprice: "14880",
                    sale: "21",
                    review: "100"
                },
                {   
                    name:"라운드토 니트 플랫 1.0 MIST79S04",
                    img: "item_8",
                    oprice: "15900",
                    dprice: "12380",
                    sale: "22",
                    review: "115"
                },
                {   
                    name:"발레리나 메리제인 플랫 HPWWFDA90Q",
                    img: "item_9",
                    oprice: "39900",
                    dprice: "37900",
                    sale: "5",
                    review: "6"
                },
                {   
                    name:"Q 메리제인 웰트 단화 1.5 MISW79S42",
                    img: "item_10",
                    oprice: "29900",
                    dprice: "18630",
                    sale: "37",
                    review: "19"
                },
                {   
                    name:"에어핏쿠션 메리제인 단화 3.0 HPWWVC407S",
                    img: "item_11",
                    oprice: "39900",
                    dprice: "23630",
                    sale: "40",
                    review: "23"
                },
                {   
                    name:"오블리크 V컷 플랫 HPWWFD201S",
                    img: "item_12",
                    oprice: "29900",
                    dprice: "27900",
                    sale: "76",
                    review: "13"
                },
                {   
                    name:"쿠션 플랫 1.0 MIST79A01",
                    img: "item_13",
                    oprice: "15900",
                    dprice: "12380",
                    sale: "22",
                    review: "103"
                },
                {   
                    name:"캔버스 슬립온 에스파듀 AFHL78S01",
                    img: "item_14",
                    oprice: "19900",
                    dprice: "14880",
                    sale: "25",
                    review: "6"
                },
                {   
                    name:"스퀘어 밴딩 바부슈 플랫 1.0 HPWWFB403M",
                    img: "item_15",
                    oprice: "19900",
                    dprice: "14880",
                    sale: "90",
                    review: "43"
                },
                {   
                    name:"글로시 메리제인 플랫 1.5 HPWWFC403S",
                    img: "item_16",
                    oprice: "29900",
                    dprice: "18630",
                    sale: "37",
                    review: "63"
                },
                {   
                   name:"[가드너] 스퀘어 메리제인 플랫슈즈 HPWWFDA03S",
                   img: "item_17",
                   oprice: "29900",
                   dprice: "27900",
                   sale: "106",
                   review: "7"
                },
                {   
                    name:"슈블리 메리제인 플랫 MIST78S52",
                    img: "item_18",
                    oprice: "39900",
                    dprice: "23630",
                    sale: "40",
                    review: "25"
                },
                {   
                    name:"포인트 민자 단화 1.0 MIST79W06",
                    img: "item_19",
                    oprice: "29900",
                    dprice: "18630",
                    sale: "37",
                    review: "8"
                },
                {   
                    name:"쭈언니픽 메리제인 컬러 니트 플랫 1.0 MIST78S04",
                    img: "item_20",
                    oprice: "19900",
                    dprice: "17900",
                    sale: "11",
                    review: "14"
                },
                {   
                   name:"메리제인 웰트 플랫 1.0 MIST79W04",
                   img: "item_17",
                   oprice: "29900",
                   dprice: "22900",
                   sale: "23",
                   review: "13" 
                },
                {   
                    name:"메리제인 발레슈 단화 1.0 HPWWVD204M",
                    img: "item_18",
                    oprice: "39900",
                    dprice: "37900",
                    sale: "5",
                    review: "17"
                },
                {   
                    name:"DRP드롭_메리제인플랫 MIST78S09",
                    img: "item_19",
                    oprice: "29900",
                    dprice: "26900",
                    sale: "10",
                    review: "15"
                },
                {   
                    name:"와이드 라운드 메리제인 단화 2.0 HPWWVD218M",
                    img: "item_20",
                    oprice: "39900",
                    dprice: "37900",
                    sale: "55",
                    review: "2"
                },
            ],
            sandal: [
                {
                    idx: 3,
                    gender: "ALL",
                    name: "패턴 커버 플랫 샌들 1.5 MIDW78S14",
                    img: "item_1",
                    oprice:"19900",
                    dprice: "16900",
                    sale:"",
                    review: "83",
                },
                {
                    idx: 4,
                    gender: "ALL",
                    name:"플랫폼 피셔맨 샌들 3.5 HPWWND204M",
                    img:"item_2",
                    oprice:"39900",
                    dprice:"35910",
                    sale:"",
                    review:"33",
                },
                // 여기부터
                {   
                    name:"스퀘어 스트랩 샌들 2.5 MIDW78S01",
                    img:"item_3",
                    oprice:"19900",
                    dprice:"14880",
                    sale:"",
                    review:"32",
                },
                {   
                    name:"와이드 플랫 피셔맨 샌들 1.0 HPWWND203M",
                    img:"item_4",
                    oprice:"39900",
                    dprice:"35910",
                    sale:"",
                    review:"26",
                },
                {   
                    name:"쿠션 투 스트랩 샌들 AFDM78S02",
                    img:"item_5",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"25",
                },
                {   
                    name:"[도영도영이 PICK] 라운드 커버 단화샌들 1.0 HPWWND201S",
                    img:"item_6",
                    oprice:"29900",
                    dprice:"26910",
                    sale:"",
                    review:"89",
                },
                {   
                    name:"[경량EVA] 아웃도어 투 벨크로 샌들 HPCV4D242M",
                    img:"item_7",
                    oprice:"39900",
                    dprice:"37900",
                    sale:"",
                    review:"1",
                },
                {   
                    name:"쿠션 플랫폼 스트랩 샌들 4.0 MIDW78S07",
                    img:"item_8",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"16",
                },
                {   
                    name:"스퀘어 스트랩 샌들 5.0 MIDW78S02",
                    img:"item_9",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"19",
                },
                {   
                    name:"X 스트랩 쿠션 웨지 샌들 6.5 MIDW78S19",
                    img:"item_10",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"19",
                },
                {   
                    name:"리커버리 소프트 젤리샌들 HPCV1D381Q",
                    img:"item_11",
                    oprice:"19900",
                    dprice:"17910",
                    sale:"",
                    review:"",
                },
                {   
                    name:"에어핏 쿠션 베이직 덮개 뮬 4.0 MIDL78S04",
                    img:"item_12",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"10",
                },
                {   
                    name:"오블리크 스트랩 샌들 2.0 MIDW78S12",
                    img:"item_13",
                    oprice:"19900",
                    dprice:"14880",
                    sale:"",
                    review:"5",
                },
                {   
                    name:"베이직 웨지 샌들 5.0 MIDW78S21",
                    img:"item_14",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"14",
                },
                {   
                    name:"스팽클 투밴드 웻지 슬리퍼 AFDL79S14",
                    img:"item_15",
                    oprice:"19900",
                    dprice:"14880",
                    sale:"",
                    review:"6",
                },
                {   
                    name:"투웨이 웨지 샌들 5.0 MIDW78S22",
                    img:"item_16",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"1",
                },
                {   
                    name:"베이직 스트랩 샌들 5.0 MIDW79S01",
                    img:"item_17",
                    oprice:"29900",
                    dprice:"22900",
                    sale:"",
                    review:"23",
                },
                {   
                    name:"메쉬 스트랩 쿠션 웨지 샌들 6.5 MIDW78S20",
                    img:"item_18",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"8",
                },
                {   
                    name:"피셔맨 힐 샌들 HPWWND252D",
                    img:"item_19",
                    oprice:"49900",
                    dprice:"44910",
                    sale:"",
                    review:"",
                },
                {   
                    name:"T스트랩 플랫폼 샌들 3.0 MIDW78S06",
                    img:"item_20",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"",
                },
            ],
        },
        bags: {
            backpack: [
                {
                    idx: 5,
                    gender: "ALL",
                    name: "푸우 레이 백팩 TPBK79S52",
                    img: "item_1",
                    oprice: "20930",
                    dprice: "18840",
                    sale:"",
                    review: "23",
                },
                {
                    idx: 6,
                    gender: "ALL",
                    name: "[테디아일랜드] 베이직 백팩 HPADZDA01C",
                    img: "item_2",
                    oprice: "23920",
                    dprice: "21530",
                    sale:"",
                    review: "1",
                },
                {
                    idx: 7,
                    gender: "ALL",
                    name: "전황일콜라보 매쉬백팩 TPBK79W72",
                    img: "item_3",
                    oprice: "48930",
                    dprice: "44040",
                    sale:"",
                    review: "10",
                },
                // 여기부터
                {
                    name:"네이비 3M 스트링 백팩 HPADZC401N",
                    img:"item_4",
                    oprice:"59900",
                    dprice:"53900",
                    sale:"",
                    review:"",
                },
                {
                    name:"[테디아일랜드] 멀티 매쉬 백팩 HPADZDA02C",
                    img:"item_5",
                    oprice:"59900",
                    dprice:"56900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"나일론 미니 백팩 BLBK78S15",
                    img:"item_6",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"3",
                },
                {
                    name:"네이비 X 베이직 백팩 HPADZC433M",
                    img:"item_7",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"MADE BY 쭈언니 백팩 BLBP78S25",
                    img:"item_8",
                    oprice:"99000",
                    dprice:"88900",
                    sale:"",
                    review:"5",
                },
                {
                    name:"마하 그리드 로고 베이직 백팩 TPBK78S71",
                    img:"item_9",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"16",
                },
                {
                    name:"브루클린 스트링 백팩 TPBK78S05",
                    img:"item_10",
                    oprice:"39900",
                    dprice:"35900",
                    sale:"",
                    review:"3",
                },
            ]     ,
            minibag: [
                {
                    idx: 8,
                    gender: "ALL",
                    name: "크로셰 핸드폰 백 BLBK78S11",
                    img: "item_1",
                    oprice: "11130",
                    dprice: "10020",
                    sale:"",
                    review: "4",
                },
                {
                    idx: 9,
                    gender: "ALL",
                    name: "나일론 셔링 미니백 HPABGD221M",
                    img: "item_2",
                    oprice: "20720",
                    dprice: "18650",
                    sale:"",
                    review: "1",
                },
                {
                    idx: 10,
                    gender: "ALL",
                    name: "데일리 나일론 미니 숄더백 HPABGC407M",
                    img: "item_3",
                    oprice: "20930",
                    dprice: "18840",
                    sale:"",
                    review: "2",
                },
                // 여기부터
                {
                    name:"캐스퍼 백인백 TPAC79W31",
                    img:"item_4",
                    oprice:"",
                    dprice:"15900",
                    sale:"",
                    review:"16",
                },
                {
                    name:"네트 핸드폰 백 BLBK78S08",
                    img:"item_5",
                    oprice:"19900",
                    dprice:"17900",
                    sale:"",
                    review:"",
                },
                {
                    name:"캐스퍼 미니 토트백 TPBT79W32",
                    img:"item_6",
                    oprice:"25900",
                    dprice:"19900",
                    sale:"",
                    review:"16",
                },
                {
                    name:"가벼운 스트링 핸드폰백 HPABXC432M",
                    img:"item_7",
                    oprice:"19900",
                    dprice:"17900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"패턴 미니백 TPBT78S06",
                    img:"item_8",
                    oprice:"",
                    dprice:"15900",
                    sale:"",
                    review:"4",
                },
                {
                    name:"뉴반달 S BLBC79W01",
                    img:"item_9",
                    oprice:"35900",
                    dprice:"27900",
                    sale:"",
                    review:"4",
                },
                {
                    name:"슈펜 베이직 핸드폰 가방 TPBC79W01",
                    img:"item_10",
                    oprice:"",
                    dprice:"15900",
                    sale:"",
                    review:"4",
                },
                {
                    name:"[NAVY] 베이직 와펜 핸드폰 가방 HPABCD205M",
                    img:"item_11",
                    oprice:"19900",
                    dprice:"18900",
                    sale:"",
                    review:"",
                },
                {
                    name:"마하 그리드 베이직 사코슈백 TPBC78S75",
                    img:"item_12",
                    oprice:"25900",
                    dprice:"22900",
                    sale:"",
                    review:"8",
                },
                {
                    name:"미니 볼링백 BLBC79W13",
                    img:"item_13",
                    oprice:"39900",
                    dprice:"30900",
                    sale:"",
                    review:"4",
                },
                {
                    name:"CHEWY MINIBAG BLBC78S20",
                    img:"item_14",
                    oprice:"",
                    dprice:"15900",
                    sale:"",
                    review:"",
                },
                {
                    name:"캔버스 아코디언 BLBC78S07",
                    img:"item_15",
                    oprice:"39900",
                    dprice:"35900",
                    sale:"",
                    review:"3",
                },
                {
                    name:"에코 미니 토트백 HPABDC456M",
                    img:"item_16",
                    oprice:"",
                    dprice:"15900",
                    sale:"",
                    review:"",
                },
                {
                    name:"바게트 미니백 HPABXC405M",
                    img:"item_17",
                    oprice:"39900",
                    dprice:"35900",
                    sale:"",
                    review:"2",
                },
                {
                    name:"클래식 미니백 HPABXC401O",
                    img:"item_18",
                    oprice:"49900",
                    dprice:"44900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"슬림 미니백 HPABXC412M",
                    img:"item_19",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"",
                },
                {
                    name:"미니스퀘어 HPABXC401M",
                    img:"item_20",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"1",
                },
            ]       

        },
        ac: {
            socks: [
                {
                    idx: 11,
                    gender: "ALL",
                    name: "슈탠다드 남녀 데일리 페이크 삭스 10팩 LGKA79A01",
                    img: "item_1",
                    oprice: "12530",
                    dprice: "11280",
                    sale:"",
                    review: "65",
                },
                {
                    idx: 12,
                    gender: "ALL",
                    name: "슈탠다드 양말_남녀 쇼트 10팩 LGKA79A21",
                    img: "item_2",
                    oprice: "12530",
                    dprice: "11280",
                    sale:"",
                    review: "5",
                },
                {
                    idx: 13,
                    gender: "ALL",
                    name: "슈탠다드 양말_남녀 클래식 골지 7팩 LGKA20A07",
                    img: "item_3",
                    oprice: "9030",
                    dprice: "8130",
                    sale:"",
                    review: "46",
                },
                // 여기부터
                {
                    name:"[슈탠다드] 여성 논슬립 풋커버 삭스 3팩 HPAO7DA13U",
                    img:"",
                    oprice:"",
                    dprice:"7900",
                    sale:"",
                    review:"",
                },
                {
                    name:"[슈탠다드] 남녀공용 5팩 페이크 삭스 (라이트웨이트) HPAO7DA11U",
                    img:"",
                    oprice:"",
                    dprice:"9900",
                    sale:"",
                    review:"",
                },
                {
                    name:"여성 골지 니삭스 HPAO2DA14Q",
                    img:"",
                    oprice:"",
                    dprice:"5900",
                    sale:"",
                    review:"2",
                },
                {
                    name:"슈탠다드 양말_여성 레귤러 무지 7팩 LGKB20A02",
                    img:"",
                    oprice:"",
                    dprice:"10000",
                    sale:"",
                    review:"7",
                },
                {
                    name:"슈탠다드 양말_여성 숏앵클 7팩 LGKB20A03",
                    img:"",
                    oprice:"",
                    dprice:"10000",
                    sale:"",
                    review:"10",
                },
                {
                    name:"여성 페이크삭스 2팩 LGKC20A01",
                    img:"",
                    oprice:"",
                    dprice:"3900",
                    sale:"",
                    review:"7",
                },
                {
                    name:"[슈탠다드] 남녀공용 쿠션 골지 크루삭스 5팩 (HPAO3CA41M RE) HPAO3DA41M",
                    img:"",
                    oprice:"",
                    dprice:"12900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"슈탠다드 양말_남녀 하프삭스 7팩 LGKA79A23",
                    img:"",
                    oprice:"",
                    dprice:"17900",
                    sale:"",
                    review:"7",
                },
                {
                    name:"서머 푸우 자수양말 2 LGKW79S13",
                    img:"",
                    oprice:"",
                    dprice:"3900",
                    sale:"",
                    review:"51",
                },
                {
                    name:"[테니스클럽] 그래픽 골지 미들 삭스 HPAO5DA17Q",
                    img:"",
                    oprice:"",
                    dprice:"5900",
                    sale:"",
                    review:"2",
                },
                {
                    name:"파스텔 컬러 골지 링클 삭스 HPAO5DA22U",
                    img:"",
                    oprice:"",
                    dprice:"3900",
                    sale:"",
                    review:"2",
                },
                {
                    name:"슈탠다드 베이직 골지 크루 삭스 5팩 HPAO3CA43M",
                    img:"",
                    oprice:"",
                    dprice:"12900",
                    sale:"",
                    review:"6",
                },
                {
                    name:"블로퍼용 페이크삭스 2팩 LGKC20A06",
                    img:"",
                    oprice:"",
                    dprice:"2900",
                    sale:"",
                    review:"13",
                },
                {
                    name:"[슈탠다드] 남녀공용 3팩 페이크 삭스 (라이트웨이트) HPAO7DA12U",
                    img:"",
                    oprice:"",
                    dprice:"7900",
                    sale:"",
                    review:"",
                },
                {
                    name:"슈탠다드 스니커즈 삭스 5팩 HPAO3CA45M",
                    img:"",
                    oprice:"",
                    dprice:"12900",
                    sale:"",
                    review:"",
                },
                {
                    name:"슈탠다드 클래식 골지 크루 삭스 5팩 HPAO3CA47M",
                    img:"",
                    oprice:"",
                    dprice:"12900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"여성 클래식 모노양말 LGKW20A01",
                    img:"",
                    oprice:"2900",
                    dprice:"2600",
                    sale:"",
                    review:"6",
                },
            ],
            hat: [
                {
                    idx: 14,
                    gender: "ALL",
                    name: "[도영도영이 PICK] 코튼 블렌드 케이블 버킷햇 HPACSD301M",
                    img: "item_1",
                    oprice: "23920",
                    dprice: "21530",
                    sale:"",
                    review: "4",
                },
                {
                    idx: 15,
                    gender: "ALL",
                    name: "아일렛 베이직 버킷햇 TPCH79W02",
                    img: "item_2",
                    oprice: "13930",
                    dprice: "12540",
                    sale:"",
                    review: "11",
                },
                {
                    idx: 16,
                    gender: "ALL",
                    name: "화섬 소프트 베이직 볼캡 TPCC79W02",
                    img: "item_3",
                    oprice: "7000",
                    dprice: "6300",
                    sale:"",
                    review: "25",
                },
                // 여기부터
                {
                    name:"[캠프 네이처] 유틸리티 스포티즘 버킷햇 HPACHD221M",
                    img:"",
                    oprice:"29900",
                    dprice:"27900",
                    sale:"",
                    review:"",
                },
                {
                    name:"쿨면 내추럴 하드 버킷햇 HPACSD305M",
                    img:"",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"",
                },
                {
                    name:"배색 포인트 니트 버킷햇 HPACSD302M",
                    img:"",
                    oprice:"29900",
                    dprice:"27900",
                    sale:"",
                    review:"",
                },
                {
                    name:"천연 라피아 스틀랩 보터햇 TPCN78S10",
                    img:"",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"라인배색 선캡 TPCN79S01",
                    img:"",
                    oprice:"19900",
                    dprice:"15900",
                    sale:"",
                    review:"4",
                },
                {
                    name:"[캠프 네이쳐] 유틸리티 스포티즘 볼캡 HPACCD223M",
                    img:"",
                    oprice:"25900",
                    dprice:"24900",
                    sale:"",
                    review:"",
                },
                {
                    name:"페이퍼 와이드 선캡 TPCN78S13",
                    img:"",
                    oprice:"19900",
                    dprice:"17900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"[테니스클럽] 테니스 그래픽 볼캡 HPACCD203M",
                    img:"",
                    oprice:"25900",
                    dprice:"24900",
                    sale:"",
                    review:"12",
                },
                {
                    name:"지사 숏 버킷햇 TPCN79S31",
                    img:"",
                    oprice:"19900",
                    dprice:"15900",
                    sale:"",
                    review:"",
                },
                {
                    name:"링클 버킷햇 HPACSD304M",
                    img:"",
                    oprice:"29900",
                    dprice:"27900",
                    sale:"",
                    review:"",
                },
                {
                    name:"네이비 N자수 볼캡 TPCC78A52",
                    img:"",
                    oprice:"19900",
                    dprice:"17900",
                    sale:"",
                    review:"3",
                },
                {
                    name:"천연 라피아 벨티드 선캡 TPCN78S12",
                    img:"",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"와이드 밴딩 선캡 TPCN79S02",
                    img:"",
                    oprice:"19900",
                    dprice:"15900",
                    sale:"",
                    review:"1",
                },
                {
                    name:"네이비 자수 버킷햇 TPCH78A51",
                    img:"",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"2",
                },
                {
                    name:"썸머 니트 와이어 벙거지 TPCN78S32",
                    img:"",
                    oprice:"19900",
                    dprice:"17900",
                    sale:"",
                    review:"5",
                },
                {
                    name:"크로셰 패턴 보닛햇 TPCN78S01",
                    img:"",
                    oprice:"19900",
                    dprice:"17900",
                    sale:"",
                    review:"2",
                },
                {
                    name:"네이비 볼록자수 볼캡 HPACCCA51M",
                    img:"",
                    oprice:"",
                    dprice:"19900",
                    sale:"",
                    review:"4",
                },
            ]
        }
    },
    men: {
        shoes: {
            sneakers: [
                {
                    idx: 17,
                    gender: "ALL",
                    name:"[슈탠다드] 와이드핏 캔버스 스니커즈 HPCR3DA03M",
                    img:"item_1",
                    oprice:"29900",
                    dprice:"27900",
                    sale:"",
                    review:"126",
                },
                {
                    idx: 18,
                    gender: "ALL",
                    name:"[슈탠다드] 베이직 캔버스 스니커즈 HPCR3DA01M",
                    img:"item_2",
                    oprice:"29900",
                    dprice:"27900",
                    sale:"",
                    review:"98",
                },
                {   
                    idx: 19,
                    gender: "ALL",
                    name:"[NAVY] 베이직 캔버스 덱 슈즈 HPCR3CA03S",
                    img:"item_3",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"9",
                },
                {   
                    idx: 20,
                    gender: "ALL",
                    name:"메쉬 스포츠 스트랩 캐주얼 AFDM78S65",
                    img:"item_4",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"6",
                },
                {   
                    idx: 21,
                    gender: "ALL",
                    name:"슬립온 니트 워킹화 AFHJ79S01",
                    img:"item_5",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"37",
                },
                // 여기부터 
                {   
                    idx: 21,
                    gender: "ALL",
                    name:"슬림핏 니트 워킹화 AFHJ79S13",
                    img:"item_6",
                    oprice:"39900",
                    dprice:"23630",
                    sale:"",
                    review:"21",
                },
                {   
                    idx: 21,
                    gender: "ALL",
                    name:"매일 신는 스니커즈 2 AFHG20S02",
                    img:"item_7",
                    oprice:"12900",
                    dprice:"12380",
                    sale:"",
                    review:"14",
                },
                {   
                    idx: 21,
                    gender: "ALL",
                    name:"베이직 스니커즈 AFHC20A02",
                    img:"item_8",
                    oprice:"12900",
                    dprice:"12380",
                    sale:"",
                    review:"214",
                },
                {   
                    idx: 21,
                    gender: "ALL",
                    name:"[테니스클럽] 리프트 코트 스니커즈 (듀얼쿠션) HPCR6D237Q",
                    img:"item_9",
                    oprice:"49900",
                    dprice:"46900",
                    sale:"",
                    review:"13",
                },
                {   
                    idx: 21,
                    gender: "ALL",
                    name:"[슈탠다드] 와이드핏 캔버스 스니커즈 HPCR3CA02S",
                    img:"item_10",
                    oprice:"",
                    dprice:"29900",
                    sale:"",
                    review:"52",
                },
                {   
                    idx: 21,
                    gender: "ALL",
                    name:"[라이트] 청키 리프트 스니커즈 (버진폼) HPCR3D232W",
                    img:"item_11",
                    oprice:"39900",
                    dprice:"37900",
                    sale:"",
                    review:"17",
                },
                {   
                    idx: 21,
                    gender: "ALL",
                    name:"위티 메리제인 슬립온 AFHJ78S06",
                    img:"item_12",
                    oprice:"29900",
                    dprice:"26900",
                    sale:"",
                    review:"14",
                },
                {   
                    idx: 21,
                    gender: "ALL",
                    name:"마하 그리드 X 슈펜 페인팅 스니커즈 AFHC78A31",
                    img:"item_13",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"1",
                },
                {   
                    idx: 21,
                    gender: "ALL",
                    name:"샌드리플운동화 AFHS79A41",
                    img:"item_14",
                    oprice:"39900",
                    dprice:"23630",
                    sale:"",
                    review:"40",
                },
                {   
                    idx: 21,
                    gender: "ALL",
                    name:"베이직 오프로드 스트링 스니커즈 AFHC79A21",
                    img:"item_15",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"10",
                },
                {   
                    idx: 21,
                    gender: "ALL",
                    name:"와이드핏 슬립온 AFHJ78S04",
                    img:"item_16",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"5",
                },
                {   
                    idx: 21,
                    gender: "ALL",
                    name:"데일리 매쉬 워킹화 AFHJ79S04",
                    img:"item_17",
                    oprice:"29900",
                    dprice:"18630",
                    sale:"",
                    review:"4",
                },
                {   
                    idx: 21,
                    gender: "ALL",
                    name:"에픽 조거 스니커즈 AFHS79A45",
                    img:"item_18",
                    oprice:"39900",
                    dprice:"23630",
                    sale:"",
                    review:"32",
                },
                {   
                    idx: 21,
                    gender: "ALL",
                    name:"조이 스니커즈 AFHC79A13",
                    img:"item_19",
                    oprice:"19900",
                    dprice:"14880",
                    sale:"",
                    review:"13",
                },
                {   
                    idx: 21,
                    gender: "ALL",
                    name:"슈레이스 니트 워킹화 HPCR5B402M",
                    img:"item_20",
                    oprice:"29900",
                    dprice:"22900",
                    sale:"",
                    review:"95",
                },
            ],

            slippers: [
                {   
                    idx: 22,
                    gender: "ALL",
                    name: "남성 피셔맨 오픈 슬라이드 HPMV4D207M",
                    img: "item_1",
                    oprice:"49900",
                    dprice: "46900",
                    sale:"",
                    review:"5",
                },
                {   
                    idx: 23,
                    gender: "ALL",
                    name: "[핏더사이즈] 남성 리커버리 슬라이드 HPMV4DA11M",
                    img: "item_2",
                    oprice:"39900",
                    dprice: "35900",
                    sale:"",
                    review:"12",
                },
                // 여기부터 
                {   
                    idx: 23,
                    gender: "ALL",
                    name: "네이비 쿠션 슬라이더 HPCV5CA02M",
                    img: "item_3",
                    oprice:"20930",
                    dprice: "18840",
                    sale:"",
                    review:"14",
                },
                {   
                    idx: 23,
                    gender: "ALL",
                    name: "바스킷 슬리퍼 AFDB20S28",
                    img: "item_4",
                    oprice:"11130",
                    dprice: "10020",
                    sale:"",
                    review:"22",
                },
                {   
                    idx: 23,
                    gender: "ALL",
                    name: "[핏더사이즈] 남성 리커버리 솔리드 클로그 HPMV4DA12M",
                    img: "item_5",
                    oprice:"55500",
                    dprice: "49950",
                    sale:"",
                    review:"1",
                },
                {   
                    idx: 23,
                    gender: "ALL",
                    name: "[핏더사이즈] 남성 리커버리 슬라이드 HPMV4DA11M",
                    img: "item_6",
                    oprice:"39900",
                    dprice: "35910",
                    sale:"",
                    review:"1",
                },
                {   
                    idx: 23,
                    gender: "ALL",
                    name: "[핏더사이즈] 남성 리커버리 버클 클로그 HPMV4DA13M",
                    img: "item_7",
                    oprice:"55500",
                    dprice: "49950",
                    sale:"",
                    review:"1",
                },
                {   
                    idx: 23,
                    gender: "ALL",
                    name: "[나이스고스트클럽X슈펜] 슬라이드 HPCV5C261M",
                    img: "item_8",
                    oprice:"13930",
                    dprice: "12540",
                    sale:"",
                    review:"4",
                },
                {   
                    idx: 23,
                    gender: "ALL",
                    name: "DRP드롭_피크닉슬라이드 AFDU78S41",
                    img: "item_9",
                    oprice:"13930",
                    dprice: "12540",
                    sale:"",
                    review:"5",
                },
                {   
                    idx: 23,
                    gender: "ALL",
                    name: "슬립온 니트 워킹화_뮬 AFHJ79S21",
                    img: "item_10",
                    oprice:"20930",
                    dprice: "18840",
                    sale:"",
                    review:"2",
                },
                {   
                    idx: 23,
                    gender: "ALL",
                    name: "코지 슬리퍼 AFDU79S21",
                    img: "item_11",
                    oprice:"11130",
                    dprice: "10020",
                    sale:"",
                    review:"6",
                },
                {   
                    idx: 23,
                    gender: "ALL",
                    name: "쿠션 투 스트랩 슬라이드 AFDM78S01",
                    img: "item_12",
                    oprice:"13930",
                    dprice: "12540",
                    sale:"",
                    review:"4",
                },
                {   
                    idx: 23,
                    gender: "ALL",
                    name: "[핏더사이즈] 레더 스웨이드 슬라이드 HPMV4DA14M",
                    img: "item_13",
                    oprice:"99000",
                    dprice: "89100",
                    sale:"",
                    review:"",
                },
                {   
                    idx: 23,
                    gender: "ALL",
                    name: "게임오버-모찌 슬리퍼 4 AFDU79S12",
                    img: "item_14",
                    oprice:"9030",
                    dprice: "8130",
                    sale:"",
                    review:"7",
                },
            ]
        },
        bags: {
            crossbag: [
                {
                    idx: 24,
                    gender: "ALL",
                    name: "마하 그리드 유틸리티 에코백 TPBT78S76",
                    img: "item_1",
                    oprice: "20,930",
                    dprice: "18,840",
                    sale: "",
                    review: "19",
                },
                {
                    idx: 25,
                    gender: "ALL",
                    name: "[드로우핏 X 슈펜] 투포켓 크로스백 HPABFC404D",
                    img: "item_2",
                    oprice: "39920",
                    dprice: "35930",
                    sale: "",
                    review: "11",
                },
                {
                    idx: 26,
                    gender: "ALL",
                    name: "전황일 패딩 버킷백 TPBT79W15",
                    img: "item_3",
                    oprice: "18130",
                    dprice: "16320",
                    sale: "",
                    review: "16",
                },
                // 여기부터
                {
                    idx: 26,
                    gender: "ALL",
                    name: "네이비 X 가벼운 크로스백 HPABXC435M",
                    img: "item_4",
                    oprice: "20930",
                    dprice: "18840",
                    sale: "",
                    review: "61",
                },
                {
                    idx: 26,
                    gender: "ALL",
                    name: "전황일콜라보 힙쌕 TPBT79W73",
                    img: "item_4",
                    oprice: "18130",
                    dprice: "16320",
                    sale: "",
                    review: "11",
                },
                {
                    idx: 26,
                    gender: "ALL",
                    name: "[NAVY] 2포켓 빅 반달 메신저백 HPABCD206M",
                    img: "item_4",
                    oprice: "31920",
                    dprice: "28730",
                    sale: "",
                    review: "",
                },
                {
                    idx: 26,
                    gender: "ALL",
                    name: "네이비 X 베이직 메신져백 HPABXC434M",
                    img: "item_4",
                    oprice: "20930",
                    dprice: "18840",
                    sale: "",
                    review: "121",
                },
                {
                    idx: 26,
                    gender: "ALL",
                    name: "마하 그리드 베이직 사코슈백 TPBC78S75",
                    img: "item_4",
                    oprice: "18130",
                    dprice: "16320",
                    sale: "",
                    review: "9",
                },
                {
                    idx: 26,
                    gender: "ALL",
                    name: "[드로우핏 X 슈펜] 투포켓 크로스백 HPABFC404D",
                    img: "item_4",
                    oprice: "39920",
                    dprice: "35930",
                    sale: "",
                    review: "66",
                },
                {
                    idx: 26,
                    gender: "ALL",
                    name: "BESLOW 캔버스 메신저백 TPBF78S07",
                    img: "item_4",
                    oprice: "20930",
                    dprice: "18840",
                    sale: "",
                    review: "2",
                },
                {
                    idx: 26,
                    gender: "ALL",
                    name: "[나이스고스트클럽X슈펜] 핸드폰 가방 HPABXC251M",
                    img: "item_4",
                    oprice: "13930",
                    dprice: "12540",
                    sale: "",
                    review: "103",
                },
                {
                    idx: 26,
                    gender: "ALL",
                    name: "[NAVY] 가벼운 반달포켓 크로스백 HPABCD207M",
                    img: "item_4",
                    oprice: "23920",
                    dprice: "21530",
                    sale: "",
                    review: "71",
                },
                {
                    idx: 26,
                    gender: "ALL",
                    name: "전황일 에코백 TPBT79S72",
                    img: "item_4",
                    oprice: "13930",
                    dprice: "12540",
                    sale: "",
                    review: "64",
                },
                {
                    idx: 26,
                    gender: "ALL",
                    name: "마하 그리드 프린트 힙쌕 TPBC78S72",
                    img: "item_4",
                    oprice: "18130",
                    dprice: "16320",
                    sale: "",
                    review: "75",
                },
                {
                    idx: 26,
                    gender: "ALL",
                    name: "[NAVY] 버클 베이직 메신저백 HPABCD201M",
                    img: "item_4",
                    oprice: "31920",
                    dprice: "28730",
                    sale: "",
                    review: "46",
                },
                {
                    idx: 26,
                    gender: "ALL",
                    name: "패커블 크로스백 HPABXC431M",
                    img: "item_4",
                    oprice: "20930",
                    dprice: "18840",
                    sale: "",
                    review: "",
                },
                {
                    idx: 26,
                    gender: "ALL",
                    name: "비슬로우 BESLOWⅩSHOOPEN 미니 크로스백 TPBF79S10",
                    img: "item_4",
                    oprice: "27930",
                    dprice: "25140",
                    sale: "",
                    review: "30",
                },
                {
                    idx: 26,
                    gender: "ALL",
                    name: "네이비 클래식 미니 에코백 TPBT78W52",
                    img: "item_4",
                    oprice: "18130",
                    dprice: "16320",
                    sale: "",
                    review: "103",
                },
            ],
            mensbag: [
                {
                    idx: 27,
                    gender: "ALL",
                    name: "비슬로우 BESLOWⅩSHOOPEN 메신저백 TPBF79S09",
                    img: "item_1",
                    oprice: "34930",
                    dprice: "31440",
                    sale: "",
                    review: "17", 
                },
                {
                    idx: 28,
                    gender: "ALL",
                    name: "비슬로우 BESLOW Ⅹ SHOOPEN 포켓 토트백 TPBF79S07",
                    img: "item_2",
                    oprice: "41930",
                    dprice: "37740",
                    sale: "",
                    review: "6", 
                },
                {
                    idx: 29,
                    gender: "ALL",
                    name: "SHOO NOTEBOOK BAG TPBF79S04",
                    img: "item_3",
                    oprice: "34930",
                    dprice: "31440",
                    sale: "",
                    review: "24", 
                },
            ]
        },
        ac: {
            belt: [
                {
                    idx: 30,
                    gender: "ALL",
                    name: "빈티지 버클 레더벨트 3.0 TPFL78A02",
                    img: "item_1",
                    oprice: "20930",
                    dprice: "18840",
                    sale: "",
                    review: "1", 
                },
                {
                    idx: 31,
                    gender: "ALL",
                    name: "FG 무봉제_벨트 TPFL79A05",
                    img: "item_2",
                    oprice: "20930",
                    dprice: "18840",
                    sale: "",
                    review: "8", 
                },
            ],
            hat: [
                {
                    idx: 33,
                    gender: "ALL",
                    name: "아일렛 베이직 버킷햇 TPCH79W02",
                    img: "item_1",
                    oprice: "13930",
                    dprice: "12540",
                    sale: "",
                    review: "19",
                },
                {
                    idx: 34,
                    gender: "ALL",
                    name: "네이비 볼록자수 볼캡 HPACCCA51M",
                    img: "item_2",
                    oprice: "13930",
                    dprice: "12540",
                    sale: "",
                    review: "44",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "슈펜 무지 볼갭 TPCC78S01",
                    img: "item_3",
                    oprice: "7000",
                    dprice: "6300",
                    sale: "",
                    review: "37",
                },
                // 여기부터
                {
                    idx: 35,
                    gender: "ALL",
                    name: "STND 버킷햇 HPACHCA56M",
                    img: "item_4",
                    oprice: "20930",
                    dprice: "18840",
                    sale: "",
                    review: "",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "STND 헤링본 버킷햇 HPACHCA55M",
                    img: "item_5",
                    oprice: "20930",
                    dprice: "18840",
                    sale: "",
                    review: "",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "투톤 베이직 볼캡 TPCC79W01",
                    img: "item_6",
                    oprice: "7000",
                    dprice: "6300",
                    sale: "",
                    review: "22",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "무지 볼캡 HPACCDA02M",
                    img: "item_7",
                    oprice: "15920",
                    dprice: "14330",
                    sale: "",
                    review: "",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "[BAMKEL] 뽀글이 군밤모자 HPAHOD109M",
                    img: "item_8",
                    oprice: "23920",
                    dprice: "21530",
                    sale: "",
                    review: "7",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "주룸 포인트 버킷햇 TPCH20W26",
                    img: "item_9",
                    oprice: "13930",
                    dprice: "12540",
                    sale: "",
                    review: "",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "STND 트윌 버킷햇 HPACHCA54M",
                    img: "item_10",
                    oprice: "20930",
                    dprice: "18840",
                    sale: "",
                    review: "",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "전황일 골지 코듀로이 버킷햇 TPCH79W73",
                    img: "item_11",
                    oprice: "20930",
                    dprice: "18840",
                    sale: "",
                    review: "3",
                },
            ]

        },
    },
    kids: {
        shoes: {
            shoe: [
                {
                    idx: 36,
                    gender: "ALL",
                    name: "키즈 플라워 매쉬 쿠션플랫 VKST78S5M",
                    img: "item_1",
                    oprice: "9900",
                    dprice: "8910",
                    sale: "",
                    review: "3",
                },
                {
                    idx: 37,
                    gender: "ALL",
                    name: "키즈 니트 말랑쿠션 플랫 VKST78S01",
                    img: "item_2",
                    oprice: "9900",
                    dprice: "8910",
                    sale: "",
                    review: "6",
                },
                {
                    idx: 38,
                    gender: "ALL",
                    name: "[레인보우] 리본 탈부착 글리터 플랫 HPKWVD224G",
                    img: "item_3",
                    oprice: "12900",
                    dprice: "11610",
                    sale: "",
                    review: "1",
                },
                // 여기부터
                {
                    idx: 35,
                    gender: "ALL",
                    name: "인어공주 조개플랫 (라이팅) VKST78S2D",
                    img: "item_4",
                    oprice: "18900",
                    dprice: "17010",
                    sale: "",
                    review: "201",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "[레인보우] 진주 라이팅 구두 HPKWFD221G",
                    img: "item_4",
                    oprice: "29900",
                    dprice: "26910",
                    sale: "",
                    review: "60",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "[레인보우] 레이스 토오픈 라이팅 구두 HPKWVD225G",
                    img: "item_4",
                    oprice: "31900",
                    dprice: "28710",
                    sale: "",
                    review: "233",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "키즈 발레리나 플랫 VKST78S03",
                    img: "item_4",
                    oprice: "",
                    dprice: "11610",
                    sale: "",
                    review: "201",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "[디즈니] 키즈 앨리스 라이팅 구두 HPKWFD21DG",
                    img: "item_4",
                    oprice: "29900",
                    dprice: "26910",
                    sale: "",
                    review: "342",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "[연주회] 베이직 플랫폼 구두 HPKWCDA11G",
                    img: "item_4",
                    oprice: "31900",
                    dprice: "28710",
                    sale: "",
                    review: "87",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "키즈 스퀘어토 로퍼 VKSL78S01",
                    img: "item_4",
                    oprice: "12900",
                    dprice: "11610",
                    sale: "",
                    review: "12",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "[레인보우] 리본 쿠션 플랫 HPKWFD201G",
                    img: "item_4",
                    oprice: "15900",
                    dprice: "14310",
                    sale: "",
                    review: "5",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "키즈 셔링 말랑 메리제인 VKST78S4M",
                    img: "item_4",
                    oprice: "11900",
                    dprice: "10710",
                    sale: "",
                    review: "7",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "키즈 메리제인 쿠션플랫 HPKWFD205G",
                    img: "item_4",
                    oprice: "12900",
                    dprice: "11610",
                    sale: "",
                    review: "16",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "키즈 니트 쿠션플랫 HPKWFD204G",
                    img: "item_4",
                    oprice: "15900",
                    dprice: "14310",
                    sale: "",
                    review: "4",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "[연주회] 키즈 진주 연주회 구두 HPKWFD212G",
                    img: "item_4",
                    oprice: "19900",
                    dprice: "17910",
                    sale: "",
                    review: "76",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "[연주회] 주얼 플랫폼 로퍼 HPKWCD213G",
                    img: "item_4",
                    oprice: "19900",
                    dprice: "17910",
                    sale: "",
                    review: "50",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "[레인보우] 키즈 리본 쿠션 플랫 HPKWFDA91G (RE HPKWFD201G)",
                    img: "item_4",
                    oprice: "15900",
                    dprice: "14310",
                    sale: "",
                    review: "32",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "키즈 쿠션플랫 VKST78S1M",
                    img: "item_4",
                    oprice: "8900",
                    dprice: "8010",
                    sale: "",
                    review: "2",
                },
            ],
            sandal: [
                {
                    idx: 39,
                    gender: "ALL",
                    name: "키즈 플라워 매쉬 쿠션플랫 VKST78S5M",
                    img: "item_1",
                    oprice: "9900",
                    dprice: "8910",
                    sale: "",
                    review: "3",
                },
                {
                    idx: 40,
                    gender: "ALL",
                    name: "키즈 니트 말랑쿠션 플랫 VKST78S01",
                    img: "item_2",
                    oprice: "9900",
                    dprice: "8910",
                    sale: "",
                    review: "6",
                },
                {
                    idx: 41,
                    gender: "ALL",
                    name: "[레인보우] 리본 탈부착 글리터 플랫 HPKWVD224G",
                    img: "item_3",
                    oprice: "12900",
                    dprice: "11610",
                    sale: "",
                    review: "151",
                },
                // 여기부터
                {
                    idx: 35,
                    gender: "ALL",
                    name: "키즈 피셔맨 플랫폼샌들 VKDW78S09",
                    img: "item_4",
                    oprice: "14900",
                    dprice: "13410",
                    sale: "",
                    review: "5",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "키즈 경량 리커버리 샌들 HPKV0D202U",
                    img: "item_5",
                    oprice: "23900",
                    dprice: "21510",
                    sale: "",
                    review: "14",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "슈펜키즈 지그재그 샌들 VKDN78S03",
                    img: "item_6",
                    oprice: "14900",
                    dprice: "13410",
                    sale: "",
                    review: "97",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "토들러 미키 라이팅 샌들 VKDM78S1D",
                    img: "item_7",
                    oprice: "18900",
                    dprice: "17010",
                    sale: "",
                    review: "31",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "후르츠 말랑 젤리슈즈 VKDJ78S03",
                    img: "item_8",
                    oprice: "9900",
                    dprice: "8910",
                    sale: "",
                    review: "11",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "키즈 소프트폼 플랫샌들 VKDW78S07",
                    img: "item_9",
                    oprice: "12900",
                    dprice: "11610",
                    sale: "",
                    review: "7",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "백설공주 샌들 (라이팅) VKDW78S2D",
                    img: "item_10",
                    oprice: "18900",
                    dprice: "17010",
                    sale: "",
                    review: "2",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "트윙클 쿠션샌들 VKDW78S03",
                    img: "item_11",
                    oprice: "14900",
                    dprice: "13410",
                    sale: "",
                    review: "102",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "슈펜키즈 트리플 밴드 샌들 VKDM78S05",
                    img: "item_12",
                    oprice: "14900",
                    dprice: "13410",
                    sale: "",
                    review: "",
                },
            ]
        },
        bags: {
            slipperbag: [
                {
                    idx: 42,
                    gender: "ALL",
                    name: "[뉴스쿨] 키즈 크로스 신발주머니 HPKBMDA02U",
                    img: "item_1",
                    oprice: "15900",
                    dprice: "14310",
                    sale: "",
                    review: "21",
                },
                {
                    idx: 43,
                    gender: "ALL",
                    name: "레디셋고 신발주머니 VKBT78S02",
                    img: "item_2",
                    oprice: "8900",
                    dprice: "8010",
                    sale: "",
                    review: "67",
                },
                {
                    idx: 44,
                    gender: "ALL",
                    name: "[뉴스쿨] 키즈 베이직 신발주머니 HPKBMDA01U",
                    img: "item_3",
                    oprice: "8900",
                    dprice: "8010",
                    sale: "",
                    review: "94",
                },
                {
                    idx: 45,
                    gender: "ALL",
                    name: "베이직 신발 주머니 VKBT79S01",
                    img: "item_4",
                    oprice: "12900",
                    dprice: "11610",
                    sale: "",
                    review: "26",
                },
                
            ],
            stylebag: [
                {
                    idx: 46,
                    gender: "ALL",
                    name: "[뉴스쿨] 키즈 슬링백 HPKBXDA01U",
                    img: "item_1",
                    oprice: "20900",
                    dprice: "18810",
                    sale: "",
                    review: "",
                },
                {
                    idx: 47,
                    gender: "ALL",
                    name: "키즈 목걸이 지갑 HPKBXDA03U",
                    img: "item_2",
                    oprice: "12900",
                    dprice: "11610",
                    sale: "",
                    review: "32",
                },
                {
                    idx: 48,
                    gender: "ALL",
                    name: "키즈 화섬 미니 크로스백 HPKBXDA02U",
                    img: "item_3",
                    oprice: "20900",
                    dprice: "18810",
                    sale: "",
                    review: "72",
                },
                {
                    idx: 49,
                    gender: "ALL",
                    name: "겨울왕국 뽀글이 크로스백 VKBX79W1D",
                    img: "item_4",
                    oprice: "14900",
                    dprice: "13410",
                    sale: "",
                    review: "19",
                },
                // 여기부터
                {
                    idx: 35,
                    gender: "ALL",
                    name: "키즈 미니 크로스백 HPKBXDA04U",
                    img: "item_5",
                    oprice: "20900",
                    dprice: "18810",
                    sale: "",
                    review: "13",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "[디즈니] 앨리스 하트 크로스백 HPKBXDA1DG",
                    img: "item_6",
                    oprice: "28900",
                    dprice: "26010",
                    sale: "",
                    review: "4",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "[슈펜키즈] 유니콘 목걸이 지갑 VKBX79S03",
                    img: "item_7",
                    oprice: "7920",
                    dprice: "7130",
                    sale: "",
                    review: "47",
                },
                {
                    idx: 35,
                    gender: "ALL",
                    name: "겨울왕국 미니백 VKBX79S1D",
                    img: "item_8",
                    oprice: "31920",
                    dprice: "28730",
                    sale: "",
                    review: "12",
                },
            ]

        },
        ac: {
            socks: [
                {
                    idx: 50,
                    gender: "ALL",
                    name: "키즈 체크 스포츠 양말 4족세트 HPKL8DA01U",
                    img: "item_1",
                    oprice: "10900",
                    dprice: "9810",
                    sale: "",
                    review: "14",
                },
                {
                    idx: 51,
                    gender: "ALL",
                    name: "키즈 스마일 스포츠 양말 4족 세트 HPKL8DA03U",
                    img: "item_2",
                    oprice: "10900",
                    dprice: "9810",
                    sale: "",
                    review: "12",
                },
                {
                    idx: 52,
                    gender: "ALL",
                    name: "키즈 치즈 스니커즈 4족 세트 HPKL4DA08U",
                    img: "item_3",
                    oprice: "8900",
                    dprice: "8010",
                    sale: "",
                    review: "",
                },
                {
                    idx: 53,
                    gender: "ALL",
                    name: "키즈 펄 레이스 양말 3족 세트 HPKL6DA03G",
                    img: "item_4",
                    oprice: "8900",
                    dprice: "8010",
                    sale: "",
                    review: "",
                },
                // 여기부터
                {
                    idx: 53,
                    gender: "ALL",
                    name: "키즈 여아 글리터 레이스 양말 4족 세트 HPKL8DA21G",
                    img: "item_5",
                    oprice: "10900",
                    dprice: "9810",
                    sale: "",
                    review: "12",
                },
                {
                    idx: 53,
                    gender: "ALL",
                    name: "키즈 골지 레이스 양말 3족 세트 HPKL6DA04G",
                    img: "item_6",
                    oprice: "8900",
                    dprice: "8010",
                    sale: "",
                    review: "263",
                },
                {
                    idx: 53,
                    gender: "ALL",
                    name: "키즈 컬러블록 스니커즈 4족 세트 HPKL4DA04U",
                    img: "item_7",
                    oprice: "8900",
                    dprice: "8010",
                    sale: "",
                    review: "83",
                },
            ],
            hat: [
                {
                    idx: 54,
                    gender: "ALL",
                    name: "키즈 메쉬 버킷햇 HPKACD201U",
                    img: "item_1",
                    oprice: "23900",
                    dprice: "21510",
                    sale: "",
                    review: "",
                },
                {
                    idx: 55,
                    gender: "ALL",
                    name: "키즈 썬캡 HPKACD203U",
                    img: "item_2",
                    oprice: "20900",
                    dprice: "18810",
                    sale: "",
                    review: "22",
                },
                {
                    idx: 56,
                    gender: "ALL",
                    name: "[테니스클럽] 키즈 배색 볼캡 HPKACDA03U",
                    img: "item_3",
                    oprice: "15900",
                    dprice: "14310",
                    sale: "",
                    review: "31",
                },
                {
                    idx: 57,
                    gender: "ALL",
                    name: "키즈 메쉬 플랩캡 HPKACD202U",
                    img: "item_4",
                    oprice: "23900",
                    dprice: "21510",
                    sale: "",
                    review: "11",
                },
                // 여기부터
                {
                    idx: 57,
                    gender: "ALL",
                    name: "키즈 솔리드 볼캡 HPKACDA02U",
                    img: "item_5",
                    oprice: "15900",
                    dprice: "14310",
                    sale: "",
                    review: "60",
                },
                {
                    idx: 57,
                    gender: "ALL",
                    name: "키즈 리버서블 버킷햇 HPKACDA01U",
                    img: "item_6",
                    oprice: "23900",
                    dprice: "21510",
                    sale: "",
                    review: "23",
                },
                {
                    idx: 57,
                    gender: "ALL",
                    name: "베이직 볼캡 VKCZ78S02",
                    img: "item_7",
                    oprice: "9900",
                    dprice: "8910",
                    sale: "",
                    review: "18",
                },
            ]
        }
    }
}

export { nbData, tgData };