const womenData = {
    item0: {
        name: "와이드 라운드 버클 단화 2.0 HPWWVD217M",
        img: "item_1",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item1: {
        name: "바게트 숄더백 HPABGD202M",
        img: "item_2",
        oprice:"",
        dprice: "39900",
        sale:"",
    },
    item2:{
        name: "네프사 캔디컬러 미들 삭스 HPAO5DA18Q",
        img: "item_3",
        oprice:"",
        dprice: "5900",
        sale:"",
    },
    item3:{
        name: "[경량EVA] 더블 스트랩 리커버리 슬리퍼 HPCV4D244M",
        img: "item_4",
        oprice:"25900",
        dprice: "24900",
        sale:"",
    },
    item4:{
        name: "[경량EVA] 아웃도어 투 벨크로 샌들 HPCV4D242M",
        img: "item_5",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item5:{
        name: "[도영도영이 PICK] 캔버스 쇼퍼백 HPABGD225M",
        img: "item_6",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item6:{
        name: "캔버스 핸드폰백 HPABGD226M",
        img: "item_7",
        oprice:"25900",
        dprice: "24900",
        sale:"",
    },
    item7:{
        name: "캔버스 버킷백 HPABGD224M",
        img: "item_8",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item8:{
        name: "[경량EVA] 논슬립 베이직 리커버리 쪼리 HPCV5D251M",
        img: "item_9",
        oprice:"19900",
        dprice: "18900",
        sale:"",
    },
    item9:{
        name: "링클 버킷햇 HPACSD304M",
        img: "item_10",
        oprice:"29900",
        dprice: "27900",
        sale:"",
    },
    item10: {
        name: "[도영도영이 PICK] 코튼 블렌드 케이블 버킷햇 HPACSD301M",
        img: "item_11",
        oprice:"29900",
        dprice: "27900",
        sale:"",
    },
    item11:{
        name: "라운드 투스트랩 밴딩 슬라이드 1.0 HPWWID231D",
        img: "item_12",
        oprice:"19900",
        dprice: "18900",
        sale:"",
    },
    item12: {
        name: "[경량EVA] 논슬립 페인팅 리커버리 쪼리 HPCV5D382M",
        img: "item_13",
        oprice:"29900",
        dprice: "27900",
        sale:"",
    },
    item13: {
        name: "[경량EVA] 컬러풀 리커버리 클로그 HPCV4D386M",
        img: "item_14",
        oprice:"35900",
        dprice: "33900",
        sale:"",
    },
    item14: {
        name: "[테니스클럽] 그래픽 골지 미들 삭스 HPAO5DA17Q",
        img: "item_15",
        oprice:"",
        dprice: "5900",
        sale:"",
    },
    item15: {
        name: "에스파듀 패턴 샌들 2.0 HPWWND321Q",
        img: "item_16",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item16: {
        name: "에스파듀 패턴 슬라이드 2.0 HPWWID321Q",
        img: "item_17",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item17: {
        name: "네이비 3M 스트링 백팩 HPADZC401N",
        img: "item_18",
        oprice:"59900",
        dprice: "53900",
        sale:"",
    },
    item18: {
        name: "밴딩 첼시 레인부츠 HPCV7D383W",
        img: "item_19",
        oprice:"35900",
        dprice: "33900",
        sale:"",
    },
    item19: {
        name: "캐스퍼 미니 토트백 TPBT79W32",
        img: "item_20",
        oprice:"25900",
        dprice: "19900",
        sale:"",
    },
}

const menData = {
    item0: {
        name: "아이스락 하이퍼그립 첼시부츠 (HPMV9C404M RE) HPMV9DA04M",
        img: "item_1",
        oprice:"",
        dprice: "159000",
        sale:"",
    },
    item1: {
        name: "[슈탠다드] 남성 컬러 골지크루 삭스 HPAO5DA19M",
        img: "item_2",
        oprice:"",
        dprice: "3900",
        sale:"",
    },
    item2: {
        name: "마하그리드 스트링 백팩 HPADZDA05M",
        img: "item_3",
        oprice:"59900",
        dprice: "56900",
        sale:"",
    },
    item3: {
        name: "[드로우핏 X 슈펜] 베이직 레더 더비 HPMR7CA51M",
        img: "item_4",
        oprice:"",
        dprice: "129000",
        sale:"",
    },
    item4: {
        name: "🌟TOP 5 [오솔라이트] 유니 레더 독일군 HPMR6DA03M",
        img: "item_5",
        oprice:"",
        dprice: "59900",
        sale:"",
    },
    item5: {
        name: "이지라이트 컴포트 어텁 레이스 펀칭더비 BYSL79A12",
        img: "item_6",
        oprice:"39900",
        dprice: "23630",
        sale:"",
    },
    item6: {
        name: "네이비 3M 스트링 백팩 HPADZC401N",
        img: "item_7",
        oprice:"59900",
        dprice: "53900",
        sale:"",
    },
    item7: { 
        name: "[핏더사이즈X슈펜] Seku-shi(세쿠시) 첼시 부읏츠 (다크 브라운 / 아이보리)",
        img: "item_8",
        oprice:"",
        dprice: "159000",
        sale:"",
    },
    item8: {
        name: "22 베이직 키높이 스니커즈_HPMR6CA04M",
        img: "item_9",
        oprice:"59900",
        dprice: "53900",
        sale:"",
    },
    item9: {
        name: "남성 레더 드라이빙로퍼_스웨이드 페니(HPMR9C471M RE) HPMR9DA11M",
        img: "item_10",
        oprice:"79900",
        dprice: "75900",
        sale:"",
    },
    item10: {
        name: "드로우핏 X 슈펜 로퍼 HPMR7DA56M",
        img: "item_11",
        oprice:"79900",
        dprice: "75900",
        sale:"",
    },
    item11: {
        name: "드로우핏 X 슈펜 더비 HPMR7DA55M",
        img: "item_12",
        oprice:"79900",
        dprice: "75900",
        sale:"",
    },
    item12: {
        name: "[초경량] 논슬립 슬림 슈레이스 워킹화 HPCR5DA23M",
        img: "item_13",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item13: {
        name: "[초경량] 논슬립 베이직 슬립온 워킹화 HPCR5DA31Q",
        img: "item_14",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item14: {
        name: "유니 모던 캐주얼 키높이 더비 HPMR7DA02M",
        img: "item_15",
        oprice:"59900",
        dprice: "56900",
        sale:"",
    },
    item15: {
        name: "유니 모던 캐주얼 로퍼 HPMR7DA04Q",
        img: "item_16",
        oprice:"59900",
        dprice: "56900",
        sale:"",
    },
    item16: {
        name: "유니모던 캐주얼 더비 HPMR7DA01Q",
        img: "item_17",
        oprice:"59900",
        dprice: "56900",
        sale:"",
    },
    item17: {
        name: "[NAVY] 2포켓 빅 반달 메신저백 HPABCD206M",
        img: "item_18",
        oprice:"39900",
        dprice: "37900",
        sale:"",
    },
    item18: {
        name: "[NAVY] 가벼운 반달포켓 크로스백 HPABCD207M",
        img: "item_19",
        oprice:"29900",
        dprice: "27900",
        sale:"",
    },
    item19: {
        name: "남성 베이직 쿠션 샌들 HPMV4D210M",
        img: "item_20",
        oprice:"59900",
        dprice: "56900",
        sale:"",
    },
}

const kidsData = {
    item0: {
        name: "키즈 썬캡 HPKACD203U",
        img: "item_1",
        oprice:"25900",
        dprice: "23310",
        sale:"",
    },
    item1: {
        name: "키즈 메쉬 플랩캡 HPKACD202U",
        img: "item_2",
        oprice:"29900",
        dprice: "26910",
        sale:"",
    },
    item2: {
        name: "키즈 메쉬 버킷햇 HPKACD201U",
        img: "item_3",
        oprice:"29900",
        dprice: "26910",
        sale:"",
    },
    item3: {
        name: "키즈 경량 EVA 샌들 HPKV0D204U",
        img: "item_4",
        oprice:"25900",
        dprice: "23310",
        sale:"",
    },
    item4: {
        name: "키즈 와이드 리커버리 샌들 HPKV0D201U",
        img: "item_5",
        oprice:"29900",
        dprice: "26910",
        sale:"",
    },
    item5: {
        name: "키즈 경량 리커버리 샌들 HPKV0D202U",
        img: "item_6",
        oprice:"29900",
        dprice: "25900",
        sale:"",
    },
    item6: {
        name: "키즈 버클 EVA 샌들 HPKV4D201U",
        img: "item_7",
        oprice:"29900",
        dprice: "25900",
        sale:"",
    },
    item7: { 
        name: "[디즈니] 앨리스 하트 크로스백 HPKBXDA1DG",
        img: "item_8",
        oprice:"35900",
        dprice: "32310",
        sale:"",
    },
    item8: {
        name: "[레인보우] 키즈 리본 쿠션 플랫 HPKWFDA91G (RE HPKWFD201G)",
        img: "item_9",
        oprice:"",
        dprice: "19900",
        sale:"",
    },
    item9: {
        name: "키즈 샤이닝 레인부츠 HPKV6DA01Q",
        img: "item_10",
        oprice:"29900",
        dprice: "26910",
        sale:"",
    },
    item10: {
        name: "[디즈니] 앨리스 라이팅 샌들 HPKWND21DG",
        img: "item_11",
        oprice:"39900",
        dprice: "35900",
        sale:"",
    },
    item11: {
        name: "[레인보우] 트윙클 쿠션 샌들 HPKWND204G",
        img: "item_12",
        oprice:"",
        dprice: "39900",
        sale:"",
    },
    item12: {
        name: "[레인보우] 하트윙 또각 굽구두 HPKWVD223G",
        img: "item_13",
        oprice:"",
        dprice: "39900",
        sale:"",
    },
    item13: {
        name: "키즈 플랫폼 베이직 샌들 HPKWND211G",
        img: "item_14",
        oprice:"29900",
        dprice: "26910",
        sale:"",
    },
    item14: {
        name: "[연주회] 키즈 주얼 연주회 구두 HPKWVD211G",
        img: "item_15",
        oprice:"39900",
        dprice: "35910",
        sale:"",
    },
    item15: {
        name: "키즈 썸머 스트랩 쿠션 샌들 HPKV4D202U",
        img: "item_16",
        oprice:"29900",
        dprice: "26910",
        sale:"",
    },
    item16: {
        name: "키즈 크레용 버클 쿠션 샌들 HPKWND212G",
        img: "item_17",
        oprice:"29900",
        dprice: "26910",
        sale:"",
    },
    item17: {
        name: "[디즈니] 앨리스 헤어핀 세트 HPKZZDA1DG",
        img: "item_18",
        oprice:"19900",
        dprice: "17910",
        sale:"",
    },
    item18: {
        name: "[레인보우] 리본 탈부착 글리터 플랫 HPKWVD224G",
        img: "item_19",
        oprice:"29900",
        dprice: "24220",
        sale:"",
    },
    item19: {
        name: "키즈 치즈 스니커즈 4족 세트 HPKL4DA08U",
        img: "item_20",
        oprice:"9900",
        dprice: "9400",
        sale:"",
    },
}

export {womenData, menData , kidsData};